### ISSUE TITLE
Renomear os arquivos Dicionario_LILACS.pdf e dicionario_MEDLINE.pdf?

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#178]
@dossanluc os arquivos https://github.com/bireme/data-governance/blob/master/LILACS_ETL/Dicionario/Dicionario_LILACS.pdf  e https://github.com/bireme/data-governance/blob/master/MEDLINE_ETL/Dicionario/dicionario_MEDLINE.pdf na verdade contêm o modelo E/R e não o dicionário, correto? Não seria o caso de renomeá-los e/ou mover para o diretorio modelo?

**Comment by dossanluc** [comment]
- Na verdade contêm o modelo E/R e não o dicionário, correto? Não seria o caso de renomeá-los e/ou mover para o diretorio modelo?
R.: De acordo, os arquivos já foram renomeados e movidos para pasta Modelo.
