### ISSUE TITLE
Campo Status aparecendo com números ao invés das designações por extenso

### ISSUE THREAD

**Issue by suelisuga** [bireme/data-governance#188]
Prezados,

Informo que na última atualização das estatísticas da LILACS os valores do campo Status apareceram como números e não suas designações por extenso:
![image](https://user-images.githubusercontent.com/13105683/74867766-05dd1080-5334-11ea-8d50-b3bcc1986252.png)

Muito obrigada!
Sueli

**Comment by dossanluc** [comment]
Sueli,
Conforme conversamos, uma nova versão foi disponibilizada, qualquer dúvida estamos a disposição.

Grato!
