### ISSUE TITLE
Aplicação Clínica da Fitoterapia para Distúrbios Metabólicos e Fisiológicos

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#202]
Processamento mapa de evidências "Aplicação Clínica da Fitoterapia para Distúrbios Metabólicos e Fisiológicos"
[Caracterizacao_Fitoterapia_Indicadores_doencas_metabolismo.xlsx](https://github.com/bireme/data-governance/files/4553033/Caracterizacao_Fitoterapia_Indicadores_doencas_metabolismo.xlsx)

**Comment by veronicaabdala** [comment]
Será necessário alterar o nome do mapa para:
Efetividade Clínica das Plantas Medicinais e Fitoterapia para Distúrbios Metabólicos e Fisiológicos

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em 

https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-doencas-metabolismo-pt/evidence-map

Fiz um agrupamento do campo Effects, pois havia algumas entradas desnormalizadas para Sem efeito.
