### ISSUE TITLE
Aplicação Clínica da Fitoterapia para Dor e Doenças Crônicas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#203]
texto sobre em português
[sobre Fitoterapia Dor Doenças Crônicas.docx](https://github.com/bireme/data-governance/files/4553096/sobre.Fitoterapia.Dor.Doencas.Cronicas.docx)

**Comment by veronicaabdala** [comment]
desconsiderar. Será necessário reprocessar este mapa

**Comment by renatomurasaki** [comment]
@veronicaabdala ok. Podemos deixar o issue aberto e quando tiver o excel atualizado, por anexar no comentario abaixo.

**Comment by renatomurasaki** [comment]
Fechando este pois foi criado o #204
