### ISSUE TITLE
Efetividade Clínica das Plantas Medicinais e Fitoterapia para Dor e Doenças Crônicas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#204]
Este mapa substituirá o mapa  "Aplicação Clínica da Fitoterapia para Dor e Doenças Crônicas". Foram acrescentados outcomes de Câncer, foram alterados alguns links para o texto completo que estava incluindo textos não abertos, correção no nome do país Índia que estava minúsculo, e os ajustes nas palavras coluna nível de confiança - alto, baixo em minúsculo.

Por favor fazer novo processamento.

[Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer.xlsx](https://github.com/bireme/data-governance/files/4553598/Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer.xlsx)

**Comment by veronicaabdala** [comment]
Por favor considerar este arquivo, identifiquei uma duplicação de estudos - da linha 321 a 369 - não sei isso foi identificado no processamento. No arquivo que segue estas linhas foram deletadas.
[Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer.xlsx](https://github.com/bireme/data-governance/files/4564873/Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado com os novos dados. Repare que os códigos do grupo de câncer estão sem título. Agrupei o campo Tipo de Revisão pois o valor Revisão Sistemática não estava normalizado. Alterado o título conforme solicitado.

**Comment by veronicaabdala** [comment]
Corrigido os nomes do grupo outcome Cancer e normalizado valor revisão sistemática campo tipo de revisão.
[Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer_5maio.xlsx](https://github.com/bireme/data-governance/files/4584096/Caracterizacao_Plantas_Medicinais_Fitoterapia_Dor_Doencas_Cronicas_Cancer_5maio.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em

https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-dor-doencas-cronicas-pt/evidence-map
