### ISSUE TITLE
Clinical Effectiveness of Medical Ozone Therapy

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#205]
Planilha de caracterização das revisões incluídas no mapa de evidências Efetividade clínica da Ozonioterapia Médica, versão inglês. Já ajustei à estrutura de mapas que está sendo aplicado, inclui a coluna effects e population, mas ficaram vazias porque estes dois dados não foram avaliados na primeira versão em português do mapa.

[Mapa_evidencias_ozonioterapia_medica_ingles.xlsx](https://github.com/bireme/data-governance/files/4560799/Mapa_evidencias_ozonioterapia_medica_ingles.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em 

https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-en/evidence-map

Falta o texto About
