### ISSUE TITLE
Efetividade Clínica da Ozonioterapia Médica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#206]
[sobre mapa ozonioterapia_30abril2020.docx](https://github.com/bireme/data-governance/files/4560825/sobre.mapa.ozonioterapia_30abril2020.docx)
Alterar o nome do Mapa "Ozonioterapia Médica" para "Efetividade Clínica da Ozonioterapia Médica" e substituir o texto sobre em português para atender ao novo padrão, sem citar nomes.

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-pt/evidence-map
