### ISSUE TITLE
Efetividade Clínica da Reflexologia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#207]
Texto "Sobre" para o mapa de evidencias "efetividade clínica da reflexologia", em português
[sobre_mapa_evidencias_Reflexologia.docx](https://github.com/bireme/data-governance/files/4562099/sobre_mapa_evidencias_Reflexologia.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala atualizado e disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/reflexologia-pt/evidence-map
