### ISSUE TITLE
Efetividade Clínica da Shantala

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#208]
Texto "sobre" o mapa de evidencias efetividade clínica da Shantala, em português.
[sobre_mapa_shantala_27abril.docx](https://github.com/bireme/data-governance/files/4562103/sobre_mapa_shantala_27abril.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/shantala-pt/evidence-map
