### ISSUE TITLE
Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#209]
Texto sobre o mapa de evidencias "Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa". Este mapa já está processado com o título "Aplicação Clínica das Práticas Corporais", se for possível, por favor alterar o título para "Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa".
[Sobre Mapa Praticas Mente Corpo Medicina Chinesa.docx](https://github.com/bireme/data-governance/files/4565041/Sobre.Mapa.Praticas.Mente.Corpo.Medicina.Chinesa.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em

https://public.tableau.com/profile/bireme#!/vizhome/praticas-corporais-pt/evidence-map
