### ISSUE TITLE
Mapa de Evidencias: Estrategias para Reducir las Desigualdades en Salud

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#214]
segue o texto "sobre" em espanhol
[sobre_mapa_equidad_español_5mayo.docx](https://github.com/bireme/data-governance/files/4583102/sobre_mapa_equidad_espanol_5mayo.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em

https://public.tableau.com/profile/bireme#!/vizhome/desigualdades-en-salud-es/evidence-map
