### ISSUE TITLE
Efetividade Clínica da Auriculoterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#215]
Texto sobre o mapa de evidências Efetividade Clínica da Auriculoterapia
[sobre_mapa_auriculoterapia.docx](https://github.com/bireme/data-governance/files/4589257/sobre_mapa_auriculoterapia.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/auriculoterapia-pt/evidence-map
