### ISSUE TITLE
Efetividade Clínica da Auriculoterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#216]
Por favor corrigir o número total de revisões do mapa de evidências efetividade clínica da auriculoterapia. Está mostrando 37 revisões e o correto é 38 revisões.

**Comment by renatomurasaki** [comment]
@veronicaabdala o número total de revisões é gerado automaticamente pela visualização. Quando isso ocorre é porque alguma revisão não está associada a uma intervenção e/ou desfecho. Nesse caso, a revisão de número 15 está associada ao desfecho C51. Repare que este código não existe na planilha Outcomes. Por favor, corrija esta revisão para reprocessamento.

**Comment by renatomurasaki** [comment]
Anexe a nova planilha neste mesmo issue, por favor.

**Comment by veronicaabdala** [comment]
corrigido. 
segue planilha para reprocessmento
[Caracterizacao_revisoes_Auriculoterapia_8Maio.xlsx](https://github.com/bireme/data-governance/files/4601962/Caracterizacao_revisoes_Auriculoterapia_8Maio.xlsx)

**Comment by renatomurasaki** [comment]
Mapa atualizado com a correção de 8 de maio e disponível em 

https://public.tableau.com/profile/bireme#!/vizhome/auriculoterapia-pt/evidence-map
