### ISSUE TITLE
Strategies to Reduce Health Inequalities 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#217]
Planilha com caracterização dos estudos para processamento do Mapa de Evidencias Estrategias para Reducir las Desigualdades en Salud - Evidence Map on Strategies to Reduce Health Inequalities 
versão inglés. 
[caracterización_revisiones_equidad_06mayo_ingles.xlsx](https://github.com/bireme/data-governance/files/4589517/caracterizacion_revisiones_equidad_06mayo_ingles.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado no idioma inglês em

https://public.tableau.com/profile/bireme#!/vizhome/desigualdades-en-salud-en/evidence-map
