### ISSUE TITLE
Strategies to Reduce Health Inequalities

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#218]
Texto sobre em inglês - mapa de evidencias Strategies to Reduce Health Inequalities
[sobre_mapa_equidad_ingles_5mayo.docx](https://github.com/bireme/data-governance/files/4589579/sobre_mapa_equidad_ingles_5mayo.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado no idioma inglês em

https://public.tableau.com/profile/bireme#!/vizhome/desigualdades-en-salud-en/evidence-map
