### ISSUE TITLE
Aportes de las MTCI para COVID-19 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#219]
Mapa de Evidencias Aportes de las MTCI para COVID-19 - versão espanhol - segue planilha para reprocessamento do mapa, espanhol, com entrada de 2 novos estudos e algumas outras correções identificadas pelo grupo de trabalho após a publicação. 
Foi solicitado indicar entre parenteses o que está considerado para cada nível de confiança, uma vez que não foi possível aplicar uma ferramenta de avaliação do nível de qualidade/confiança dos estudos.  Está indicado na coluna "confidence level", por favor veja se é possível. Uma outra opção, caso a informação esteja muito larga, é indicar a seguinte legenda:
círculo verde - Revisiones Sistemáticas; círculo amarelo -  RCTs y Revisiones No Sistemáticas; círculo vermelho - Estudios No Randomizados
Neste caso, não precisa as palavras alto, bajo, moderado na frente de cada círculo.
[Caracterizacao-Estudos-covid19-mtci_espanol_6mayo.xlsx](https://github.com/bireme/data-governance/files/4589634/Caracterizacao-Estudos-covid19-mtci_espanol_6mayo.xlsx)

**Comment by veronicaabdala** [comment]
[Sobre_mapa_covid_mtci_11mayo_español.docx](https://github.com/bireme/data-governance/files/4612630/Sobre_mapa_covid_mtci_11mayo_espanol.docx)
Segue o texto atualizado sobre o mapa covid-mtci em espanhol

**Comment by renatomurasaki** [comment]
Mapa e sobre atualizados em espanhol e disponíveis em

https://public.tableau.com/profile/bireme#!/vizhome/mtci-covid-es/evidence-map
