### ISSUE TITLE
Efetividade Clínica das Plantas Medicinais e Fitoterapia para Saúde Mental e Qualidade de Vida

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#220]
Planilha de caracterização de revisòes para o mapa de evidências "Efetividade Clínica das Plantas Medicinais e Fitoterapia para Saúde Mental e Qualidade de Vida
[Caracterizacao_Fitoterapia_g_i_h.xlsx](https://github.com/bireme/data-governance/files/4596426/Caracterizacao_Fitoterapia_g_i_h.xlsx)
"

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-s-mental-q-vida-pt/evidence-map

No aguardo do texto de Sobre. Realizei agrupamento de valores nos campos Focus Country e Confidence Level por problemas de normalização.
