### ISSUE TITLE
Alteras fonte de dados das visualizações do Tableau Public - Global Index Médicos

### ISSUE THREAD

**Issue by dossanluc** [bireme/data-governance#224]
- Baixar as visualizações de Global Index Médicos do Tableau Public
- Passar a visualizações para o online
- https://public.tableau.com/profile/bireme#!/

**Comment by dossanluc** [comment]
Baixar as visualizações de Global Index Médicos do Tableau Public
- A visualização [infometrics-gim-aim](https://public.tableau.com/profile/bireme/#!/vizhome/infometrics-gim-aim/Story1) atualizada para usar a base PostgreSql já esta atualizada no Tableau public.

**Comment by dossanluc** [comment]
- A visualização [infometrics-gim-imemr](https://public.tableau.com/profile/bireme/#!/vizhome/infometrics-gim-imemr/Story1) atualizada para usar a base PostgreSql já esta atualizada no Tableau public.

**Comment by dossanluc** [comment]
A visualização [infometrics-gim-imsear](https://public.tableau.com/profile/bireme/#!/vizhome/infometrics-gim-imsear/Story1) atualizada para usar a base PostgreSql já esta atualizada no Tableau public.

**Comment by renatomurasaki** [comment]
@dossanluc revisei a visualização IMSEAR e está ok! Obrigado!

**Comment by dossanluc** [comment]
Atualizações de Global Index Médicos realizadas com sucesso!
