### ISSUE TITLE
Aportes das MTCI/PICS para COVID-19

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#226]
Mapa de Evidencias Aportes das MTCI/PICS para COVID-19 - versão português - segue planilha para reprocessamento do mapa, português, com entrada de 2 novos estudos e algumas outras correções identificadas pelo grupo de trabalho após a publicação.
Foi solicitado indicar entre parenteses o que está considerado para cada nível de confiança, uma vez que não foi possível aplicar uma ferramenta de avaliação do nível de qualidade/confiança dos estudos. Está indicado na coluna "confidence level", por favor veja se é possível. Uma outra opção, caso a informação esteja muito larga, é indicar a seguinte legenda:
círculo verde - Revisões Sistemáticas; círculo amarelo - RCTs e Revisões não Sistemáticas; círculo vermelho - Estudos não Randomizados
Neste caso, não precisa as palavras alto, baixo, moderado na frente de cada círculo.

Segue também o texto "sobre" atualizado, em português
[Caracterizacao-Estudos-covid19-mtci_portugues_8maio.xlsx](https://github.com/bireme/data-governance/files/4601837/Caracterizacao-Estudos-covid19-mtci_portugues_8maio.xlsx)
[Texto sobre_mapa_covid_mtci_portugues_8maio.docx](https://github.com/bireme/data-governance/files/4601840/Texto.sobre_mapa_covid_mtci_portugues_8maio.docx)

**Comment by veronicaabdala** [comment]
[Sobre_mapa_covid_mtci_11maio_portugues.docx](https://github.com/bireme/data-governance/files/4612615/Sobre_mapa_covid_mtci_11maio_portugues.docx)

Por favor considerar este texto sobre o Mapa de evidencias COVID-MTCI, pois tivemos que incluir informações importantes sobre o alcance do mapa - uma nota tipo disclaimer, por recomendação.

A alteração também foi feita nos idiomas ingles e espanhol, vou enviar em issue separado.

**Comment by renatomurasaki** [comment]
Mapa e sobre atualizados na versão português e disponível em

https://public.tableau.com/profile/bireme#!/vizhome/mtci-covid-pt/evidence-map
