### ISSUE TITLE
Clinical Effectiveness of Medical Ozone Therapy

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#228]
segue texto sobre em inglês para o mapa de evidencias Efetividade Clínica da Ozoniotera Clinical / Clinial Effectiveness of Medical Ozone Therapy
[sobre mapa ozonioterapia_medica_ingles_8maio.docx](https://github.com/bireme/data-governance/files/4601920/sobre.mapa.ozonioterapia_medica_ingles_8maio.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado em https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-en/evidence-map
