### ISSUE TITLE
Evidence Map on the contributions of TCIM in the context of COVID-19

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#229]
Segue Planilha de caracterização dos estudos do mapa de evidencias COVID-MTCI em inglês, e texto sobre.
Evidence Map on the contributions of Traditional, Complementary, and Integrative Medicine (TCIM) in the context 
[Caracterizacao-Estudos-covid19-mtci_ingles_11maio.xlsx](https://github.com/bireme/data-governance/files/4613050/Caracterizacao-Estudos-covid19-mtci_ingles_11maio.xlsx)
[Sobre_mapa_covid_mtci_11maio_ingles.docx](https://github.com/bireme/data-governance/files/4613051/Sobre_mapa_covid_mtci_11maio_ingles.docx)

of COVID-19

**Comment by renatomurasaki** [comment]
Mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/mtci-covid-en/evidence-map
