### ISSUE TITLE
 Efetividade Clínica das Plantas Medicinais e da Fitoterapia para Dor, Doenças Crônicas e Câncer

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#233]
Texto sobre Mapa de evidências - Efetividade Clínica das Plantas Medicinais e da Fitoterapia para Dor, Doenças Crônicas e Câncer
[sobre_mapa_Fitoterapia_Dor_Doenças_Crônicas_Câncer.docx](https://github.com/bireme/data-governance/files/4652606/sobre_mapa_Fitoterapia_Dor_Doencas_Cronicas_Cancer.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala texto de sobre publicado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-dor-doencas-cronicas-pt/evidence-map
