### ISSUE TITLE
Efetividade Clínica Fitoterapia e Plantas Medicinais para Saúde Mental e Qualidade de Vida

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#239]
Segue texto sobre o mapa de evidencias Efetividade Clínica Fitoterapia e Plantas Medicinais para Saúde Mental e Qualidade de Vida
[sobre_fitoterapia_ saude_Mental_Qualidade_de_Vida.docx](https://github.com/bireme/data-governance/files/4724155/sobre_fitoterapia_.saude_Mental_Qualidade_de_Vida.docx)

**Comment by renatomurasaki** [comment]
Atualizado texto de Sobre e disponivel em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-s-mental-q-vida-pt/evidence-map
