### ISSUE TITLE
Efetividade Clínica Fitoterapia e Plantas Medicinais para Disturbios Fisiológicos e Metabólicos

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#240]
Segue texto sobre o mapa de evidencias Efetividade Clínica Fitoterapia e Plantas Medicinais para Disturbios Fisiológicos e Metab
[sobre_Fitoterapia_Disturbios_Metabolicos_Fisiologicos .docx](https://github.com/bireme/data-governance/files/4724159/sobre_Fitoterapia_Disturbios_Metabolicos_Fisiologicos.docx)
ólicos

**Comment by renatomurasaki** [comment]
Texto de Sobre atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-doencas-metabolismo-pt/evidence-map
