### ISSUE TITLE
Efetividade Clínica da Fitoterapia e Plantas Medicinais para Cicatrização e Doenças Agudas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#241]
Segue planilha de caracterização de estudos para o mapa de evidencias Efetividade Clínica da Fitoterapia e Plantas Medicinais para Cicatrização e Doenças Agudas
[Caracterizacao_Fitoterapia_cicatrizacao+doencas_agudas.xlsx](https://github.com/bireme/data-governance/files/4725482/Caracterizacao_Fitoterapia_cicatrizacao%2Bdoencas_agudas.xlsx)

**Comment by veronicaabdala** [comment]
quando podemos ter este mapa publicado? São 4 mapas da Fitoterapia, mas o relatório será apenas 1, e o grupo está aguardando este ultimo mapa para fazer o relatorio. obrigada,

**Comment by renatomurasaki** [comment]
@veronicaabdala esse issue tinha ficado no limbo. com a atualização do issue consegui ver que tinha este pendente. Esta semana ainda o publicaremos.

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-cicatrizacao-doencas-agudas-pt/evidence-map

**Comment by veronicaabdala** [comment]
Por favor corrigir o título do Mapa. O correto é : Efetividade Clínica da Fitoterapia e Plantas Medicinais para Cicatrização e Doenças Agudas

**Comment by renatomurasaki** [comment]
Atualizado
