### ISSUE TITLE
Atualizar visualização ODS3 / Agenda 2030 com os dados atualizados do ETL

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#246]
https://lilacs.bvsalud.org/es/infometrias-lilacs/salud-y-bienestar-ods-3-agenda-2030-indicadores-de-la-produccion-cientifica-y-tecnica-en-lilacs/

@dossanluc por favor, precisa atualizar asap para reportar ao Ministério da Saúde

**Comment by dossanluc** [comment]
Dados atualizados com a base de dados do ETL

**Comment by dossanluc** [comment]
Dashboard disponível no Tableau Public.
