### ISSUE TITLE
Atualizar visualização ASSA2030 com os dados atualizados do ETL

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#247]
https://lilacs.bvsalud.org/es/infometrias-lilacs/objetivos-de-la-agenda-de-salud-sostenible-para-las-americas-assa2030/

@dossanluc por favor, precisa atualizar asap para reportar ao Ministério da Saúde

**Comment by dossanluc** [comment]
Dados atualizados com a base de dados do ETL

**Comment by dossanluc** [comment]
Dashboard disponível no Tableau Public.
