### ISSUE TITLE
Atualizar visualização Eixos Transversais com os dados atualizados do ETL

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#248]
https://lilacs.bvsalud.org/es/infometrias-lilacs/genero-equidad-etnicidad-y-derechos-humanos-indicadores-de-la-produccion-tecnico-y-cientifica-disponible-en-lilacs/

@dossanluc por favor, precisa atualizar asap para reportar ao Ministério da Saúde

**Comment by dossanluc** [comment]
Dados atualizados com a base de dados do ETL

**Comment by dossanluc** [comment]
Dashboard disponível no Tableau Public.
