### ISSUE TITLE
Cria visualização para Infometria Lilacs BDENF

### ISSUE THREAD

**Issue by dossanluc** [bireme/data-governance#255]
Criar uma visualização para Infometria Lilacs BDENF com base na visualização Informetria Lilacs ODS3.

**Comment by dossanluc** [comment]
**Dados do portal de pesquisa**
	-- 46.312
**Dados do ETL**
	-- 24.030

**### Analise dos dados FI-Admin**
select * from database_database where acronym = 'BDENF';
-- 4

select count(id) from biblioref_reference_indexed_database where database_id = 4;
-- 23569

select 	count(rf.id)  
from	biblioref_reference as rf 	left join biblioref_referencealternateid as al on 
		rf.id = al.reference_id 	left join biblioref_reference_indexed_database AS idb ON 
		rf.id = idb.reference_id 	left join database_database AS adb ON 
		idb.database_id = adb.id	
where 	adb.acronym = 'BDENF';
-- 23569

**Comment by dossanluc** [comment]
Primeira versão disponível para validação da visualização [infometria-lilacs-bdenf](https://public.tableau.com/profile/bireme#!/vizhome/infometria-lilacs-bdenf/Histria1)

**Comment by dossanluc** [comment]
Alterações
- nome para infometria-bdenf
- nome Historia1 para dashboard
- alterar titulos
	1 - Infometria BDENF
	2 - Indicadores de la producción técnico y científica disponible en BDENF
- retirar o link da LILACS
- ajustar o layout dos painéis para se adaptarem a história 1 para evitar as rolagens verticais e horizontais												OK
- ordenar decrescente
- eliminar as colunas e deixar somente os totais por assunto e por autor
- analise no filtros para verificar quantidade de dados

**Comment by dossanluc** [comment]
Alterações finalizadas, Dashboard disponível para validação. ([infometria-bdenf](https://public.tableau.com/profile/bireme/#!/vizhome/infometria-bdenf/Dashboard))

**Comment by dossanluc** [comment]
Alterações
- Alterar formato da legenda
- Filtrar por tipo de descritores em 4 planilhas
- Retirar a palavra null no inicio do nome do autor

Alterações finalizadas, Dashboard disponível para validação. ([infometria-bdenf](https://public.tableau.com/profile/bireme#!/vizhome/infometria-bdenf/Dashboard))

**Comment by renatomurasaki** [comment]
Verificar a diferença de aprox. 3 mil documentos a menos na visualição, comparado com a interface iAHx da BVS Regional

**Comment by dossanluc** [comment]
A visualização foi criada com sucesso, agora vamos realizar atualizações e correções, nas visualizações e processo de carga de dados. 
As próximas tarefas serão tratadas em outra issue!
