### ISSUE TITLE
Mapa de evidencia: Aplicação clínica da Ozonioterapia Bucal

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#257]
Por favor reprocessar o mapa de evidencia Aplicação clínica da Ozonioterapia Bucal, foram excluídos alguns outcomes.

**Comment by veronicaabdala** [comment]
[Caracterizacao_Ozonio_Bucal_8abril_e.xlsx](https://github.com/bireme/data-governance/files/4926666/Caracterizacao_Ozonio_Bucal_8abril_e.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado
