### ISSUE TITLE
Mapa de Evidencias: Antibiotic Prophylaxis for Surgical Procedures

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#259]
Por favor processar novo mapa de evidencias "Antibiotic Prophylaxis for Surgical Procedures" em inglês somente. Solicito uma alteração do label do campo "interventions" para "comparators" para representar a intervenção controle. Na planilha já está com o nome comparators (coluna D)

**Comment by veronicaabdala** [comment]
[Evidence_Map_Anbiotics_caracterizacion_final_aug10.xlsx](https://github.com/bireme/data-governance/files/5056891/Evidence_Map_Anbiotics_caracterizacion_final_aug10.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala lembre-se que o nome das colunas NÃO DEVEM ser alterados, pois isso quebra o processamento. Favor manter o nome Interventions em todas as planilhas que foram alteradas.

O uso do termo Comparators será alterado somente na visualização.

**Comment by veronicaabdala** [comment]
Obrigada Renato, anotado, não alterar nomes das colunas. E alterando o nome no label super resolve.

**Comment by veronicaabdala** [comment]
Renato, tem uma precisão de quando o mapa será processado e publicado? Estamos escrevendo um artigo sobre o tema e o mapa está referenciado e analisado no artigo. Obrigada,

**Comment by veronicaabdala** [comment]
[Evidence_Map_Anbiotics_caracterizacion_final_aug27.xlsx](https://github.com/bireme/data-governance/files/5139491/Evidence_Map_Anbiotics_caracterizacion_final_aug27.xlsx)
Segue planilha corrigida - interventions e outcomes group

**Comment by renatomurasaki** [comment]
Mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/antibiotic-prophylaxis-surgical-procedures-en/evidence-map

Há um erro no Excel: a primeira planilha que contém os metadados das evidências deve se chamar RS e estava SR, o que ocasionava um erro no processamento dos dados. O nome da planilha se comporta como se fosse o nome de uma tabela e não deve ser alterado.
