### ISSUE TITLE
Mapa de Evidências: Efetividade clínica da Acupuntura

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#260]
Segue planilha com caracterização dos estudos para o mapa de evidências "Efetividade clínica da Acupuntura" e texto sobre
[Acupuntura_Versão_Final_Caracterização_Revisoes_12agosto.xlsx](https://github.com/bireme/data-governance/files/5062994/Acupuntura_Versao_Final_Caracterizacao_Revisoes_12agosto.xlsx)
[Resumo acupuntura para o site.docx](https://github.com/bireme/data-governance/files/5062995/Resumo.acupuntura.para.o.site.docx)

**Comment by renatomurasaki** [comment]
Mapa disponível em https://public.tableau.com/profile/bireme#!/vizhome/acupuntura-pt/evidence-map

@veronicaabdala demoramos para processar porque foi dificil de encontrar o erro que estava dando no Interventions Group. Finalmente vimos que as células A2-A8 da planilha "Interventions" estavam mescladas (merge). Conforme já conversado, a estrutura de nomes de colunas e células das planilhas não podem ser alteradas. Retirei o merge e repliquei o mesmo dado "Acupuntura" nas células A2-A8 e voltou a funcionar a visualização. Lembre-se que o Excel é ao mesmo tempo a entrada de dados e a base de dados para processar os mapas.
