### ISSUE TITLE
Atualizar registros migrados.

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/data-governance#262]
@lcorreasantos , por favor, coletar do FI-ADMIN os  Índices a seguir para a base de estatísticas 
LIPECS
SES-SP
ColecionaSUS
PrevCan

Grata

**Comment by anakatiacamilo** [comment]
Boa tarde, @dossanluc  tirando o LIPECS que foi resolvido em outro issue, será que você consegue deixar agendando a Coleta das bases: SES-SP, ColecionaSUS, PrevCan
E também a bases LILACS com o Status Migrado -3
Grata

**Comment by dossanluc** [comment]
Boa tarde, @anakatiacamilo , não é possível agendar, esse processo por se tratar de exeção tem que rodar em horário escolhido.
Entre hoje e amanhã, vou tentar rodar essas bases SES-SP, ColecionaSUS, PrevCan.
Mas essa solicitação (LILACS com o Status Migrado -3), tem que alterar o processo para atender o filtro de Status, não sei se conseguimos a tempo.

**Comment by anakatiacamilo** [comment]
@dossanluc , Obrigada. O da LILACS posso abrir um outro issue e vejo com o @heitorbarbieri quando ele voltar de férias.

**Comment by dossanluc** [comment]
O dados foram atualizados conforme abaixo:
bases SES-SP - Todos OK
ColecionaSUS - Todos OK
PrevCan - Até 03/10 estara disponível.
