### ISSUE TITLE
Mapa de Evidencias: Antibiotic Prophylaxis for Surgical Procedures

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#264]
Solicito reprocessamento do Mapa de Evidencias: Antibiotic Prophylaxis for Surgical Procedures, há correção em um grupo de outcomes. obrigada,
[Evidence_Map_Anbiotics_caracterizacion_final_Set3.xlsx](https://github.com/bireme/data-governance/files/5174863/Evidence_Map_Anbiotics_caracterizacion_final_Set3.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala esse mapa tinha ficado no limbo e consegui resgatá-lo. Mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/antibiotic-prophylaxis-surgical-procedures-en/evidence-map

Repare que este mapa ainda não tem o texto de About/Sobre.
