### ISSUE TITLE
Mapa de evidências "Efetividade clínica da Acupuntura"

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#265]
Por favor reprocessar este mapa de acordo com a planilha. Havia dois estudos com o mesmo título e com id iguais, mas são estudos diferentes. Também foi feita alteração no texto sobre.
[Acupuntura_Versão_Final_Caracterização_Revisoes_7setembro.xlsx](https://github.com/bireme/data-governance/files/5184588/Acupuntura_Versao_Final_Caracterizacao_Revisoes_7setembro.xlsx)
[Resumo acupuntura para o site.docx](https://github.com/bireme/data-governance/files/5184590/Resumo.acupuntura.para.o.site.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa e seu respectivo texto de sobre atualizados.
