### ISSUE TITLE
Mapa de evidencias efetividade-clinica-das-plantas-medicinais-e-fitoterapia-para-saude-mental-e-qualidade-de-vida

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#268]
Neste mapa não está funcionando nenhum link para os artigos - texto completo - 
https://mtci.bvsalud.org/pt/efetividade-clinica-das-plantas-medicinais-e-fitoterapia-para-saude-mental-e-qualidade-de-vida/

**Comment by renatomurasaki** [comment]
@veronicaabdala por alguma razão o Tableau não reconheceu o campo ID do Excel e por isso não montava a URL. Agora está funcionando.
