### ISSUE TITLE
Mapa de evidencias efetividade-clinica-das-plantas-medicinais-e-fitoterapia-para-saude-mental-e-qualidade-de-vida

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#271]
Este mapa precisa ser reprocessado, foram feitas algumas correções nos dados. 

[Caracterizacao_Fitoterapia_saude_mental_qualidade_vida_17set.xlsx](https://github.com/bireme/data-governance/files/5270559/Caracterizacao_Fitoterapia_saude_mental_qualidade_vida_17set.xlsx)

**Comment by renatomurasaki** [comment]
Mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/fitoterapia-s-mental-q-vida-pt/evidence-map
