### ISSUE TITLE
Atualização por Índice

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/data-governance#274]
Por favor, 
Fazer atualiza no ETL a base de dados BDENF.
Eu poderia tem um usuário ou a permissão de fazer atualização por índice no pentaho ?
Grata

**Comment by renatomurasaki** [comment]
@anakatiacamilo estamos avaliando a reestruturação do servidor do PENTAHO pois o mesmo está travando na execução dos processos de ETL do FI-Admin, o que vem ocasionando paralização da atualização da base COVID-19 por problemas de memória.

Todo sábado ocorre automaticamente a atualização de 15d do ETL que deveria incluir a BDENF. Verifique se na segunda-feira 19/oct o ETL estará atualizado com os dados da BDENF.

**Comment by anakatiacamilo** [comment]
Índice atualizado, e Infometria atualizada tb #316
