### ISSUE TITLE
Mapa de Evidencias: Efetividade Clínica da Ozonioterapia Bucal

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#275]
Envio mapa de evidencias ozonioterapia bucal para reprocessamento. A planilha foi completamente revisada e também o texto sobre.
Este mapa substituirá o anterior.
[sobre_mapa_Ozonio_Bucal_18nov2020.docx](https://github.com/bireme/data-governance/files/5562223/sobre_mapa_Ozonio_Bucal_18nov2020.docx)
[Caracterizacao_Ozonio_Bucal_18nov.xlsx](https://github.com/bireme/data-governance/files/5562224/Caracterizacao_Ozonio_Bucal_18nov.xlsx)

**Comment by renatomurasaki** [comment]
Mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-bucal-pt/evidence-map

Com a mudança nas intervenções, essa atualização acabou criando de fato um outro mapa.
