### ISSUE TITLE
Mapa de evidências - Efetividade Clínica da prática do Yoga

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#284]
Por favor reprocessar o Mapa de evidências Efetividade Clínica da prática do Yoga, que foi revisado e atualizado pelo grupo de trabalho. 
Também atualizar a informação sobre.

[sobre_mapa_yoga_3fev21.docx](https://github.com/bireme/data-governance/files/5973847/sobre_mapa_yoga_3fev21.docx)
[Caracterizacao_revisoes_yoga_7fev21.xlsx](https://github.com/bireme/data-governance/files/5973848/Caracterizacao_revisoes_yoga_7fev21.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/yoga-pt/evidence-map
