### ISSUE TITLE
Mapa de Evidências - Clinical Effectiveness of Medical Ozone Therapy

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#285]
Por favor reprocessar o mapa  Clinical Effectiveness of Medical Ozone Therapy, versão inglês e português. Foram feitas atualizações de links para o texto completo, alterado o nome de um grupo de desfecho na versão inglês, e alterado um grupo de intervenção nas duas versões ingles e português.
Os dois textos sobre não precisam de ajustes porque as mudanças não alteraram os principais resultados.  

[Mapa_evidencias_ozonioterapia_ingles_17fev21.xlsx](https://github.com/bireme/data-governance/files/5998681/Mapa_evidencias_ozonioterapia_ingles_17fev21.xlsx)
[Mapa_evidencias_ozonioterapia_17fev21.xlsx](https://github.com/bireme/data-governance/files/5998682/Mapa_evidencias_ozonioterapia_17fev21.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em:
- versão português: https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-pt/evidence-map
- versão inglês: https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-en/evidence-map
