### ISSUE TITLE
Mapa de evidências - Efetividade Clínica da Laserterapia na Saúde Bucal

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#286]
Processar novo mapa de evidências "Efetividade Clínica da Laserterapia na Saúde Bucal" a partir da planilha de caracterização anexada. Segue também o texto sobre. 

[sobre_mapa_evidencia_laser_final.docx](https://github.com/bireme/data-governance/files/6012998/sobre_mapa_evidencia_laser_final.docx)
[Mapa_laserterapia_ 18fev21xlsx.xlsx](https://github.com/bireme/data-governance/files/6012999/Mapa_laserterapia_.18fev21xlsx.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala há dois problemas na planilha que precisam ser corrigidos:

- Renomear a coluna "Intervention Group" da aba "Interventions" para "Interventions Group"
- O campo País/Região como Foco precisa de normalização. Há opções "Não reportado", "Não informado", "Paquistão, Malásia" (deve usar ;)

A versão atual do mapa está disponível em https://public.tableau.com/profile/bireme#!/vizhome/laserterapia-pt/evidence-map

Favor enviar o Excel atualizado neste mesmo issue.

**Comment by veronicaabdala** [comment]
Putz!!! Quase gabaritei! Revisei inúmeras vezes. Desculpa aí, obrigada. Já corrigi 

Enviado do meu iPhone

**Comment by renatomurasaki** [comment]
Envie novamente a planilha com o campo País como Foco normalizado, por favor.

**Comment by veronicaabdala** [comment]
[Mapa_laserterapia_final_25fev.xlsx](https://github.com/bireme/data-governance/files/6075744/Mapa_laserterapia_final_25fev.xlsx)
Enviando a planilha corrigida

**Comment by veronicaabdala** [comment]
Reenviando o texto sobre com uma correção. Por favor substituir. 
[sobre_mapa_evidencia_laser_final_5mar21.docx](https://github.com/bireme/data-governance/files/6090626/sobre_mapa_evidencia_laser_final_5mar21.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e publicado em https://public.tableau.com/profile/bireme#!/vizhome/laserterapia-pt/evidence-map
