### ISSUE TITLE
Mapa de Evidências “Aplicação Clínica da Ozonioterapia no Tratamento da COVID-19”

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#287]
Enviando planilha de caracterização de estudos clínicos (não tem revisão sistemática) para o mapa de Evidências “Aplicação Clínica da Ozonioterapia no Tratamento da COVID-19”. 
Nota importante: O nível de confiança não pode ser indicado com o Instrumento AMSTAR2 que se aplica para Revisões Sistemáticas. Assim, foi indicado o nível de confiança de acordo com o tipo de estudo. Por favor fazer aparecer a legenda de cor da bolha de acordo com o indicado na coluna "confidence level". 
Enviando também o texto sobre.
[mapa ozonioterapia covid-19_final_10mar.xlsx](https://github.com/bireme/data-governance/files/6117585/mapa.ozonioterapia.covid-19_final_10mar.xlsx)
[resumo_mapa_evidencias_ozonio_covid.docx](https://github.com/bireme/data-governance/files/6117586/resumo_mapa_evidencias_ozonio_covid.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala vou tentar priorizá-lo, mas lembre-se que o SLA definido para processamento dos mapas é de até 2 semanas, para responder à contraparte.

**Comment by veronicaabdala** [comment]
Eu tinha prá mim que era 1 semana. Mas tudo bem... obrigada,

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa processado e publicado, disponível em https://public.tableau.com/profile/bireme#!/vizhome/ozonioterapia-covid-pt/evidence-map
