### ISSUE TITLE
Mapa de Evidências sobre Yoga

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#288]
Enviando planilha de caracterização de estudos para processamento de novo Mapa de Evidências sobre Yoga.
[mapa_yoga_SES_SP.xlsx](https://github.com/bireme/data-governance/files/6130753/mapa_yoga_SES_SP.xlsx)
[Resumo do mapa_Yoga_SES_SP.docx](https://github.com/bireme/data-governance/files/6130754/Resumo.do.mapa_Yoga_SES_SP.docx)

**Comment by veronicaabdala** [comment]
Se for possível, poderia usar "Baixo ou criticamente baixo" para o nível de confiança baixo? Eu ajustei isso na planilha e reenvio a planilha. E este será o padrão para os próximos mapas. 
[mapa_yoga_SES_SP.xlsx](https://github.com/bireme/data-governance/files/6130842/mapa_yoga_SES_SP.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala já existe um mapa sobre yoga. Qual seria o título deste mapa para diferenciá-los? O mapa existente se chama "Mapa de evidências - Efetividade Clínica da prática do Yoga".

**Comment by renatomurasaki** [comment]
@veronicaabdala além do título, preciso de uma palavra para diferenciar as URLs do mapa. Por exemplo, o mapa existente de yoga leva na URL a string "/yoga-pt/evidence-map". Como ficaria para este novo mapa?

**Comment by renatomurasaki** [comment]
@veronicaabdala me dê uma palavra que resuma "dor crônica e aguda, obesidade e sobrepeso, tabagismo, saúde mental e segurança" para que eu possa diferenciar as URL do mapa existente de yoga e este novo.

**Comment by veronicaabdala** [comment]
Pode ser duas palavras? Qualidade de Vida

**Comment by veronicaabdala** [comment]
Falei com o grupo da Tereza e eles preferem: Yoga e Hatha Yoga

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/yoga-hatha-yoga-pt/evidence-map
