### ISSUE TITLE
Mapa de Evidências sobre Medicina Tradicional Chinesa

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#289]
Enviando planilha de caracterização de estudos clínicos para novo Mapa de Evidências sobre Medicina Tradicional Chinesa.
Este mapa tem apenas 3 estudos clínicos, não são revisões sistemáticas porque não foram encontradas revisões para os critérios de inclusão definidos pelo grupo que fez o mapa.
No campo "nível de confiança", por favor considerar o label como está indicado, ou seja:
círculo verde - Alto (Baixo risco de viés)
círculo amarelo - Moderado (Risco de viés incerto)
círculo vermelho
[mapa_mtc_SES_SP.xlsx](https://github.com/bireme/data-governance/files/6130802/mapa_mtc_SES_SP.xlsx)
[Resumo do mapa_MTC_SES_SP.docx](https://github.com/bireme/data-governance/files/6130803/Resumo.do.mapa_MTC_SES_SP.docx)

 - Baixo (Alto risco de viés)

**Comment by veronicaabdala** [comment]
Corrigindo: 
No campo "nível de confiança", por favor considerar o label como está indicado, ou seja:
círculo verde - Alto (Baixo risco de viés)
círculo amarelo - Moderado (Risco de viés incerto)
círculo vermelho - Baixo (Alto risco de viés)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/medicina-tradicional-chinesa-pt/evidence-map
