### ISSUE TITLE
Mapa de Evidências sobre Meditação e Mindfulness 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#290]
Enviando planilha de caracterização de estudos para geração do Mapa de Evidências sobre Meditação e Mindfulness 
e texto sobre. 
nota: todos os estudos estão classificados como baixo ou criticamente baixo para o campo "nível de confiança", portanto todos vão estar no círculo vermelho. 

[mapa_meditação_SES_SP.xlsx](https://github.com/bireme/data-governance/files/6141310/mapa_meditacao_SES_SP.xlsx)
[Resumo do mapa_Meditação_SES_SP.docx](https://github.com/bireme/data-governance/files/6141311/Resumo.do.mapa_Meditacao_SES_SP.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala já existe um mapa sobre meditação. Qual seria o título deste mapa para diferenciá-los? O mapa existente se chama "Mapa de evidências - Efetividade Clínica da Meditação".

**Comment by renatomurasaki** [comment]
@veronicaabdala além da questão do titulo, é preciso alterar a coluna A da aba outcomes para retirar o merge das celulas do grupo B.

**Comment by veronicaabdala** [comment]
O título deste mapa é "Mapa de Evidências sobre Meditação e Mindfulness" 
É um mapa diferente do outro, foi feito pelo grupo da Dra Tereza Toma, do Instituto de Saúde de SP. Eu alertei sobre esta duplicidade e eles fizeram uma comparação do conteúdos dos mapas, e identificaram pouca sobreposição. Ainda assim, foi proposto um trabalho de grupo para juntar os mapas. 

Desculpa pelo erro de merge na aba outcomes, já corrigi. Segue planilha corrigida.

[mapa_meditação_SES_SP.xlsx](https://github.com/bireme/data-governance/files/6185476/mapa_meditacao_SES_SP.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/meditacao-mindfulness-pt/evidence-map

Ainda acho que para o usuário final, temos dois mapas com títulos muito similares, apesar das intervenções e desfechos serem diferentes, assim como o Sobre.
