### ISSUE TITLE
Mapa de Evidências sobre Acupuntura e Auriculoterapia 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#291]
Enviando planilha para processamento do Mapa de Evidências sobre Acupuntura e Auriculoterapia e texto sobre.
[mapa_acupuntura_final_17mar.xlsx](https://github.com/bireme/data-governance/files/6159248/mapa_acupuntura_final_17mar.xlsx)
[Resumo do mapa_Acupuntura_final.docx](https://github.com/bireme/data-governance/files/6159249/Resumo.do.mapa_Acupuntura_final.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala já existem dois mapas, um para acupuntura e outro para auriculoterapia, cujos títulos são, respectivamente "Mapa de evidências - Efetividade Clínica da Acupuntura" e "Mapa de evidências - Efetividade Clínica da Auriculoterapia". Qual seria o título deste mapa para diferenciá-los?

**Comment by renatomurasaki** [comment]
@veronicaabdala vamos publicar este mapa com o título "Mapa de Evidências sobre Acupuntura e Auriculoterapia"?

**Comment by veronicaabdala** [comment]
Sim Renato, é o mesmo caso da Meditação. Este mapa foi também trabalhado pelo grupo da Tereza Toma, do Instituto de Saúde, e tem algumas diferenças, embora tenha alguma sobreposição de revisões. 
Por favor publicar com este título: "Mapa de Evidências sobre Acupuntura e Auriculoterapia" 
E vamos indicar os dois mapas na BVS MTCI Américas.
Obrigada,

**Comment by renatomurasaki** [comment]
Mapa publicado em https://public.tableau.com/profile/bireme#!/vizhome/acupuntura-auriculoterapia-pt/evidence-map
