### ISSUE TITLE
Mapa de evidências - Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#292]
Atualizar o texto sobre do Mapa de evidências -
[Resumo sobre Mapa Mind-Body_18mar21.docx](https://github.com/bireme/data-governance/files/6166985/Resumo.sobre.Mapa.Mind-Body_18mar21.docx)
 Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa

**Comment by renatomurasaki** [comment]
@veronicaabdala texto de sobre atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/praticas-corporais-pt/evidence-map
