### ISSUE TITLE
Mapa de Evidências Redução da Mortalidade Materna

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#293]
Enviando a planilha de caracterização dos estudos para o Mapa de Evidências Redução da Mortalidade Materna. 
Nota: No nível de confiança tem 4 itens, solicito considerar a cor cinza (usada em protocolos) para o nível de confiança "criticamente baixo". 
E o texto sobre enviarei em separado. 
Sobre o prazo de processamento e publicação, por favor considerar que este mapa será lançado no dia 6 de maio no V Congresso de Atenção Primária, que a Bireme está apoiando. 

[Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx](https://github.com/bireme/data-governance/files/6313612/Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala está ocorrendo erro no processamento porque o Excel não tem a coluna Type of Review. Mesmo que vocês não estejam utilizando este dado, o formato do arquivo Excel NÃO PODE ser alterado. Apenas não informem mas mantenham a coluna

**Comment by renatomurasaki** [comment]
@veronicaabdala outra pergunta: criticamente baixo é pior que baixo?

**Comment by veronicaabdala** [comment]
[Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx](https://github.com/bireme/data-governance/files/6320652/Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx)
reenviando a planilha corrigida

**Comment by renatomurasaki** [comment]
@veronicaabdala o mapa está processado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/mortalidade-materna-pt/evidence-map

Duas coisas:
- me confirme se criticamente baixo é pior que baixo
- veja que a intervenção "Labetalol" não pertence a nenhum grupo (aparece nulo)

Aguardo planilha atualizada e texto sobre.

**Comment by veronicaabdala** [comment]
sim, criticamente baixo é pior que baixo
corrigida a intervenção labetalol no grupo "manejo clínico", corrigido na planilha

[Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx](https://github.com/bireme/data-governance/files/6320888/Caracterizacao_Mapa_Mortalidade_Materna_14abril_FINAL.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/mortalidade-materna-pt/evidence-map

**Comment by veronicaabdala** [comment]
Solicito o reprocessamento do mapa considerando uma correção de código de outcome e alteração de nome de um grupo de outcome. 
Também envio o texto sobre do mapa "redução da mortalidade materna".
E solicito a inclusão do filtro população no mapa.
[Caracterizacao_Mapa_Mortalidade_Materna_23Abril.xlsx](https://github.com/bireme/data-governance/files/6365657/Caracterizacao_Mapa_Mortalidade_Materna_23Abril.xlsx)
[Resumo do mapa_mortalidade_materna.docx](https://github.com/bireme/data-governance/files/6365658/Resumo.do.mapa_mortalidade_materna.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/mortalidade-materna-pt/evidence-map
