### ISSUE TITLE
Mapa de evidências - Efetividade Clínica da Shantala

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#294]
Envio planilha atualizada de caracterização dos estudos para o Mapa de evidências - Efetividade Clínica da Shantala
E texto sobre também atualizado.

[Caracterizacao_Shantala_28abr2021.xlsx](https://github.com/bireme/data-governance/files/6394698/Caracterizacao_Shantala_28abr2021.xlsx)
[sobre_mapa_shantala_28abril2021.docx](https://github.com/bireme/data-governance/files/6394699/sobre_mapa_shantala_28abril2021.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em https://public.tableau.com/profile/bireme#!/vizhome/shantala-pt/evidence-map. O filtro tipo de estudo foi eliminado pois este campo está vazio na planilha.
