### ISSUE TITLE
Mapa de Evidências sobre Leishmaniose Visceral 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#295]
Envio planilha de caracterização e texto sobre o Mapa de Evidências sobre Leishmaniose Visceral, para processamento e publicação do mapa.
[LV_Caracterizacao_Revisões_Final_7jun.xlsx](https://github.com/bireme/data-governance/files/6610006/LV_Caracterizacao_Revisoes_Final_7jun.xlsx)
[Resumo do mapa_LV_7jun.docx](https://github.com/bireme/data-governance/files/6610008/Resumo.do.mapa_LV_7jun.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa processado e publicado em
https://public.tableau.com/app/profile/bireme/viz/leishmaniose-visceral-pt/evidence-map
