### ISSUE TITLE
Criar infometria para Saúde Digital baseado em dados da LILACS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#296]
Arquivos de tabulação disponíveis na bismuto01, gerados a partir do issue https://github.com/bireme/db-processing/issues/478

**Comment by anakatiacamilo** [comment]
Infometria pronta em espanhol

https://public.tableau.com/app/profile/bireme/viz/infometria-lilacs-telemedicina-es/Histria1
