### ISSUE TITLE
Mapa de Evidencias Leishmaniose Visceral - Português

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#302]
Por favor reprocessar o mapa de evidencias LV, com atualização.

[Português_LV_Caracterizacao_25agosto.xlsx](https://github.com/bireme/data-governance/files/7060876/Portugues_LV_Caracterizacao_25agosto.xlsx)
[Resumo do mapa_LV (português) revisado_26agosto.docx](https://github.com/bireme/data-governance/files/7060877/Resumo.do.mapa_LV.portugues.revisado_26agosto.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa atualizado e disponível em https://public.tableau.com/app/profile/bireme/viz/leishmaniose-visceral-pt/evidence-map
