### ISSUE TITLE
Mapa de evidencias Leishmaniose visceral - Español

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#303]
Por favor processar mapa Leishmaniose visceral - versão español
[Español_LV_Caracterizacao_25agosto.xlsx](https://github.com/bireme/data-governance/files/7060887/Espanol_LV_Caracterizacao_25agosto.xlsx)
[Resumo do mapa_LV (espanhol) revisado 26 agosto.docx](https://github.com/bireme/data-governance/files/7060888/Resumo.do.mapa_LV.espanhol.revisado.26.agosto.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/app/profile/bireme/viz/leishmaniose-visceral-es/evidence-map
