### ISSUE TITLE
Mapa de evidências Leishmaniose visceral - versão inglês

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#304]
Por favor processar mapa Leishmaniose visceral - versão inglês
[English_LV_Caracterizacao_25agosto.xlsx](https://github.com/bireme/data-governance/files/7060895/English_LV_Caracterizacao_25agosto.xlsx)
[Resumo do mapa_LV (inglês) revisado 26agosto.docx](https://github.com/bireme/data-governance/files/7060896/Resumo.do.mapa_LV.ingles.revisado.26agosto.docx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa publicado em https://public.tableau.com/app/profile/bireme/viz/leishmaniose-visceral-en/evidence-map

**Comment by veronicaabdala** [comment]
Vamos precisar reprocessar este mapa - versão inglês para corrigir uma inconsistência campo país foco. 
[English_LV_Caracterizacao_8fev2022.xlsx](https://github.com/bireme/data-governance/files/8026587/English_LV_Caracterizacao_8fev2022.xlsx)
