### ISSUE TITLE
Mapa de Evidências Má Nutrição e Intervenções na APS

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#309]
@renatomurasaki enviando planilha para processamento do Mapa de Evidências Má Nutrição e intervenções na APS. O texto curto ainda não está disponível, enviarei em separado.
[Caracterizacao_Revisões_Mapa_Má_Nutrição_final_8out21.xlsx](https://github.com/bireme/data-governance/files/7312182/Caracterizacao_Revisoes_Mapa_Ma_Nutricao_final_8out21.xlsx)

**Comment by renatomurasaki** [comment]
@veronicaabdala mapa processado e disponível em https://public.tableau.com/app/profile/bireme/viz/ma-nutricao-aps-pt/evidence-map

Encontrarmos no campo "Focus Country" a ocorrência do país Corea. Nesse processamento, estamos considerando que Corea é Coréia do Sul. Caso não seja, favor reenviar a planilha Excel atualizada.

Aguardamos envio do arquivo Word de Sobre.
