### ISSUE TITLE
Map of Evidence in Ozone therapy for treatment of COVID-19

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#310]
Por favor processar a versão inglês do mapa Ozonio e COVID-19 - Map of Evidence in Ozone therapy for treatment of COVID-19
Segue a planilha e o texto sobre resumido.

[resumo_mapa_evidencias_ozonio_covid_ingles_28.06.21.docx](https://github.com/bireme/data-governance/files/7470475/resumo_mapa_evidencias_ozonio_covid_ingles_28.06.21.docx)
[mapa.ozonioterapia.covid-19_final_ingles_3nov21.xlsx](https://github.com/bireme/data-governance/files/7470476/mapa.ozonioterapia.covid-19_final_ingles_3nov21.xlsx)

**Comment by anakatiacamilo** [comment]
Publicado em:
https://public.tableau.com/app/profile/bireme/viz/template-evidence-map-en/evidence-map?publish=yes

**Comment by veronicaabdala** [comment]
Katia, este mapa foi reprocessado mas não apresenta os termos interventions, outcomes e filtros em inglês de acordo com a planilha enviada. Estou reenviando a planilha para reprocessamento, por favor.
[mapa.ozonioterapia.covid-19_atualizado_ingles_29mar22.xlsx](https://github.com/bireme/data-governance/files/8457193/mapa.ozonioterapia.covid-19_atualizado_ingles_29mar22.xlsx)
[resumo_mapa_evidencias_ozonio_covid_ingles_29mar22.docx](https://github.com/bireme/data-governance/files/8457194/resumo_mapa_evidencias_ozonio_covid_ingles_29mar22.docx)
