### ISSUE TITLE
Texto resumido sobre Mapa de Evidencias Má Nutrição

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#311]
Por favor aplicar o texto sobre o mapa de evidencias já publicado - https://public.tableau.com/app/profile/bireme/viz/ma-nutricao-aps-pt/evidence-map 
[Resumo do mapa_Ma_Nutricao.docx](https://github.com/bireme/data-governance/files/7470516/Resumo.do.mapa_Ma_Nutricao.docx)

**Comment by anakatiacamilo** [comment]
Texto Aplicado.
