### ISSUE TITLE
Mapa de evidencias Efetividade Clínica das Plantas Medicinais e da Fitoterapia para Saúde Mental e Qualidade de Vida

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#312]
Por favor reprocessar o mapa de evidências - Efetividade Clínica das Plantas Medicinais e da Fitoterapia para Saúde Mental e Qualidade de Vida, foi encontrado um erro. O mapa já está publicado, precisa reprocessar e substituir.

Caracterizacao_Fitoterapia_saude_mental_qualidade_vida_11nov21.xlsx
[Caracterizacao_Fitoterapia_saude_mental_qualidade_vida_11nov21.xlsx](https://github.com/bireme/data-governance/files/7521875/Caracterizacao_Fitoterapia_saude_mental_qualidade_vida_11nov21.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado https://public.tableau.com/app/profile/bireme/viz/fitoterapia-s-mental-q-vida-pt/evidence-map
