### ISSUE TITLE
Mapa de evidências - Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#313]
Por favor reprocessar o Mapa de evidências - Efetividade Clínica das Práticas Mente e Corpo da Medicina Tradicional Chinesa, que foi corrigido um dado. Também substituir o texto resumo sobre o mapa.
[Sobre Mapa Praticas Mente Corpo Medicina Chinesa 18nov21.docx](https://github.com/bireme/data-governance/files/7564908/Sobre.Mapa.Praticas.Mente.Corpo.Medicina.Chinesa.18nov21.docx)
[Caracterizacao_Revisoes_praticas_final_18Nov21.xlsx](https://github.com/bireme/data-governance/files/7564909/Caracterizacao_Revisoes_praticas_final_18Nov21.xlsx)

**Comment by anakatiacamilo** [comment]
Na lista de Países/Região Foco Arrumei os erro de escrita, mas não agrupei:
- Holanda e Países Baixos;
- Europa e União Europeia

Por favor, manter a mesma ordem nas colunas para facilitar o processamento do mapa.

Mapa Atualizado

**Comment by veronicaabdala** [comment]
[Caracterizacao_Revisoes_praticas_final_24nov21.xlsx](https://github.com/bireme/data-governance/files/7597955/Caracterizacao_Revisoes_praticas_final_24nov21.xlsx)
Reenviando a planilha com os países de foco corrigidos. E qual é a ordem das colunas que vc tem no processamento? Me passa a ordem para eu considerar no envio das proximas planilhas de mapas. obrigada,

**Comment by anakatiacamilo** [comment]
Ordem correta:
Number	Title	Interventions Group	Interventions	Outcomes Group	Outcomes	Effects 	Population	Database	Id	Confidence Level	Type of Review	Study Design	Review Design	Focus Country	Publication Country	Publication Year	Full Text	Citation

Ordem enviada:
	Title	Interventions Group	Interventions	Outcomes Group	Outcomes	Effects 	Population	Database	Id	Publication Country	Focus Country	Publication Year	Type of Review	Review Design	Study Design	Confidence Level	Full Text	Citation

Corrigi a ordem desta tabela e atualizei o Mapa conforme o ultimo arquivo.
