### ISSUE TITLE
Mapa de Evidências Efetividade Clínica da Moxabustão

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#315]
Por favor processar o Mapa de Evidências Efetividade Clínica da Moxabustão de acordo com a planilha em anexo. O texto sobre será elaborado, deixar em branco esta informação por enquanto.
[Mapa Moxabustão_planilha_final_22nov.xlsx](https://github.com/bireme/data-governance/files/7584715/Mapa.Moxabustao_planilha_final_22nov.xlsx)

**Comment by anakatiacamilo** [comment]
Por favor, manter a ordem das coluna para facilitar o processamento:
Number Title Interventions Group Interventions Outcomes Group Outcomes Effects Population Database Id Confidence Level Type of Review Study Design Review Design Focus Country Publication Country Publication Year Full Text Citation

Mapa de Evidencia disponivel https://public.tableau.com/app/profile/bireme/viz/moxabustao-pt/evidence-map?publish=yes
