### ISSUE TITLE
Evidence Gap Map Interventions to Reduce Household Air Pollution

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#318]
Por favor processar e publicar o mapa de evidencias "Interventions to Reduce Household Air Pollution" versão inglês, considerando o seguinte parâmetro para distribução do campo "CONFIDENCE LEVEL"  nas bolhas:

Cor verde - Systematic review 
Cor Azul - Non-systematic review
Cor Laranja - Policy and program analysis
Cor Cinza - Scientific event

O texto curto resumo será enviado posteriormente.

[Matriz caracterización Mapa HAP_final_2dic21.xlsx](https://github.com/bireme/data-governance/files/7642062/Matriz.caracterizacion.Mapa.HAP_final_2dic21.xlsx)

**Comment by anakatiacamilo** [comment]
Mapa de evidencia publicado, por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/template-evidence-map-en/evidence-map?publish=yes

**Comment by veronicaabdala** [comment]
Incluir filtro população

**Comment by anakatiacamilo** [comment]
Já tinha o filtro de Population no template em inglês

**Comment by veronicaabdala** [comment]
Por favor publicar a informação sobre deste mapa. obrigada

[Resumen de informe Mapa de evidencia_Dic13_v2.docx](https://github.com/bireme/data-governance/files/7728449/Resumen.de.informe.Mapa.de.evidencia_Dic13_v2.docx)

**Comment by anakatiacamilo** [comment]
Atualizado
https://public.tableau.com/app/profile/bireme/viz/reduce-household-air-pollution-en/evidence-map
