### ISSUE TITLE
Infometria do COVID-19

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/data-governance#319]
Criar um dashboard da Infometria do COVID-19

@botturam, por favor, disponibilizar os arquivos para analise.

**Comment by botturam** [comment]
@anakatiacamilo seguem os locais onde estão os CSVs do COVID-WHO:

1) COVID-principal: /bases/lilG4/cvd.lil/COVIDWHO_tab (COVIDWHO_tabulacoes.zip)
2) COVID-grey:       /bases/lilG4/grc.lil/GREY-COVIDWHO_tab (GREY-COVIDWHO_tabulacoes.zip)
3) COVID-preprint: /bases/lilG4/ppc.lil/PREPRINT-COVIDWHO_tab  (PREPRINT-COVIDWHO_tabulacoes.zip)

**Comment by anakatiacamilo** [comment]
@heitorbarbieri, @botturam 
Segue a url da primeira versão da Infometria
https://public.tableau.com/app/profile/bireme/viz/Teste_covid19/Histria1?publish=yes

**Comment by anakatiacamilo** [comment]
Filtros: Country, Jornal, Autor, Lang, Year, DataBase
Action 
1 -  Mapa, os filtros e as listas dos filtros;
2 - Distribuição dos usuário por país por um periodo: Mapa + lista de país + Total de usuários - Google Analytic
3 - Crescimento de documentos por mês de publicação + total de documentos 

@botturam, Por favor, atualizar os arquivos da COVID-19 para infometria e colocar a informação de mês de publicação

@heitorbarbieri a informação do Google Analytic

**Comment by anakatiacamilo** [comment]
@botturam, por favor, atualizar as tabulações dos registros enriquecidos para atualização da Infometria 

drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 COVIDWHO_FULL_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 elsevier_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 LILACS_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 mdl20_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 mdl21_tab/
-rw-rw-r-- 1 operacao operacao 593 Dec 9 16:14 NOTAS
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 PAHOIRIS_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 WHOIRIS_tab/
drwxrwsr-x 2 operacao operacao 4096 Dec 9 16:18 WPRIM_tab/

Grata

**Comment by botturam** [comment]
@anakatiacamilo já está tudo atualizado (07/03/2021) em:

operacao@serverofi5:/bases/lilG4/covid_enriched_CSV $ ll
total 40
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:33 COVIDWHO_FULL_tab/
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:31 elsevier_tab/
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:33 LILACS_tab/
drwxrwsr-x 4 operacao operacao 4096 Mar  8 15:39 mdl20_tab/
drwxrwsr-x 4 operacao operacao 4096 Mar  8 15:43 mdl21_tab/
drwxrwsr-x 2 operacao operacao 4096 Mar  8 16:40 mdl22_tab/
-rw-rw-r-- 1 operacao operacao  630 Dec  9 16:41 NOTAS_vs1
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:53 PAHOIRIS_tab/
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:52 WHOIRIS_tab/
drwxrwsr-x 3 operacao operacao 4096 Mar  8 15:53 WPRIM_tab/

**Comment by botturam** [comment]
já coloquei as tabulações em /bases/lilG4/covid_enriched_CSV

lembrando que vc não usa o não enriquecido COVIDWHO_FULL_tab/

as tabulações de dezembro (primeira) estão mantidas nos subdiretórios vs1/

**Comment by anakatiacamilo** [comment]
Segue o link da Infometry COVID-19 WHO

https://public.tableau.com/app/profile/bireme/viz/InfometryCOVID-19WHO/Histria1

Aguardo seus comentários

**Comment by anakatiacamilo** [comment]
Filtro de autor:
 - Trocar o campo de autor da bases MEDLINE AU ==>> FAU;
 - Arrumar os primeiros nomes no filtro

**Comment by anakatiacamilo** [comment]
@heitorbarbieri, solicitou uma nova proposta de dashbord.

- Todas as informações em uma página;
- Alterações nos títulos;
- Tirar todos os filtros suspensos:
- No grafico de mês de publicação: 
   - Substituir os mês 00 por --
   - Colocar um subtotal por ano - Não é possivel no grafico só na tabela.
   - tira os títulos dos campos que estão em português.
- Trocar o Mapa de país de publicação por uma tabela;
- Incluir as Regiôes - Como não tem esta informação no dado utilizei este site https://en.wikipedia.org/wiki/List_of_WHO_regions, por favor, verificar se esta correto.
- Incluir uma lista com o título dos Documentos - Não foi possivel, porque eu trabalho com 4 tabelas do processamento do COVID-19 e nenhuma delas tem o títluo, o título do documentos esta na tabela lilacs_id_titulo_idioma.txt que eu não faço tratamento para a infometria.
 
[PropostaHeitor.pdf](https://github.com/bireme/data-governance/files/8430118/PropostaHeitor.pdf)

Segue o link 

https://public.tableau.com/app/profile/bireme/viz/InfometryCOVID-19WHOversion1_2/Heitor

**Comment by anakatiacamilo** [comment]
https://public.tableau.com/app/profile/bireme/viz/InfometryCOVID-19WHOversion1_3/Heitor2?publish=yes

**Comment by anakatiacamilo** [comment]
Todos os metadados 500 mil (+enriquecidos)
Botão de limpar filtros
Data da ultima atualização

Analisar performace
Campo de perquisa em Descritores e Autor
* Outros idiomas (espanhol)

**Comment by anakatiacamilo** [comment]
@botturam, por favor, atualizar as bases do COVID-19

**Comment by heitorbarbieri** [comment]
@anakatiacamilo segue um link que te ajudará na conferência dos países:

https://worldpopulationreview.com/country-rankings/list-of-countries-by-continent

**Comment by heitorbarbieri** [comment]
@anakatiacamilo, poderemos liberar o link da infometria para o pessoal do COVID/WHO na semana que vem para que eles iniciem a fase de testes?

**Comment by heitorbarbieri** [comment]
@anakatiacamilo, apenas registrando como sugestão para uma futura versão, a inclusão de dois botões em cada tabela: um ordena por label e outro por valor numérico.

https://playfairdata.com/how-to-change-sort-order-with-buttons-in-tableau/

**Comment by anakatiacamilo** [comment]
https://www.who.int/countries
