### ISSUE TITLE
Mapa de Evidencias Má Nutrição - texto resumo

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#322]
Por favor atualizar o resumo - sobre - o mapa de evidencias má nutrição já publicado. 
[Resumo do mapa_Ma_Nutricao atualizado 8dez21.docx](https://github.com/bireme/data-governance/files/7677719/Resumo.do.mapa_Ma_Nutricao.atualizado.8dez21.docx)

**Comment by anakatiacamilo** [comment]
Atualizado
https://public.tableau.com/app/profile/bireme/viz/ma-nutricao-aps-pt/evidence-map

**Comment by veronicaabdala** [comment]
Incluir filtro População

**Comment by anakatiacamilo** [comment]
Atualizado

**Comment by anakatiacamilo** [comment]
O Interventions group que mais é afetado com a mudança de horizontal para vertical não era Psicologia era Farmacológica - Atualizado
