### ISSUE TITLE
Mapa de Evidências Sequelas da COVID-19 Pós-Aguda

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#323]
Por favor reprocessar o Mapa de Evidências Sequelas da COVID-19 Pós-Aguda considerando vários ajustes/correções na planilha de caracterização. Por favor publicar o **grupo de intervenções **na vertical**** (diminuindo a largura da primeira coluna) e os **outcomes também na vertical**. 
Substituir o novo texto resumo do mapa.
[Caracterizacao_mapa_evidencias_covid_sequelas_final_10dez.xlsx](https://github.com/bireme/data-governance/files/7694887/Caracterizacao_mapa_evidencias_covid_sequelas_final_10dez.xlsx)
[sobre_mapa_sequelas_covid_10dez.docx](https://github.com/bireme/data-governance/files/7694888/sobre_mapa_sequelas_covid_10dez.docx)

**Comment by veronicaabdala** [comment]
Incluir filtro população

**Comment by anakatiacamilo** [comment]
Atualizado conforme a solicitação
https://public.tableau.com/app/profile/bireme/viz/sequelas-covid-pos-aguda-pt/evidence-map

**Comment by veronicaabdala** [comment]
Por favor considerar a nova planilha com atualizações, reenvio o arquivo. Aproveito para consultar se é possível diminuir a altura das linhas para melhorar a usabilidade do mapa. abraço e obrigada
[Caracterizacao_mapa_evidencias_covid_sequelas_final_10dez.xlsx](https://github.com/bireme/data-governance/files/7703686/Caracterizacao_mapa_evidencias_covid_sequelas_final_10dez.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado

**Comment by veronicaabdala** [comment]
Por favor reprocessar o mapa de acordo com a planilha que segue em anexo
[Caracterizacao_mapa_evidencias_covid_sequelas_final_15dez.xlsx](https://github.com/bireme/data-governance/files/7722191/Caracterizacao_mapa_evidencias_covid_sequelas_final_15dez.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, o problema não é o Título ainda estou investigando.

**Comment by anakatiacamilo** [comment]
@veronicaabdala, descobri o problema não é o título se quiser voltar ao original, o problema e o campo de Population esta vazio, precisa estar preenchido.

**Comment by anakatiacamilo** [comment]
Atualizado

**Comment by veronicaabdala** [comment]
Por favor agregar mais uma aba como o título Mapa de Evidência (por efeito) considerando como variável o campo de dado "effects" no lugar do campo "nível de confiança". 
Se for possível, manter o mesmo link do mapa já publicado - https://public.tableau.com/app/profile/bireme/viz/sequelas-covid-pos-aguda-pt/evidence-map 
[Caracterizacao_mapa_evidencias_covid_sequelas_final_12maio2022.xlsx](https://github.com/bireme/data-governance/files/8682713/Caracterizacao_mapa_evidencias_covid_sequelas_final_12maio2022.xlsx)

**Comment by veronicaabdala** [comment]
Mapa de Evidência (por nível de confiança) - na aba que já existe

**Comment by veronicaabdala** [comment]
proposta de cores para legenda dos efeitos para nova aba que está sendo criada:
Positivo - verde bandeira
Potencial Positivo - verde claro
Negativo - vermelho
Potencial negativo - laranja
Sem efeito - Rosa claro 
Misturado - Azul Bic
Não informado - Cinza

**Comment by veronicaabdala** [comment]
Por favor, na primeira aba deste Mapa (que já existe), aplicar o nome:  Mapa de Evidência (por tipo de estudo) e considerar as cores de acordo com a legenda sugerida pelo DECIT, mostrada na imagem que segue anexada. 

O DECIT também solicitou alteração nas cores das células que mostram os grupos de intervenções e desfechos - veja na imagem anexada. 


![Mapa_de_Evidências (1)](https://user-images.githubusercontent.com/26144462/168658561-c32af601-beaa-4796-bd73-bcae0f487041.png)
![cores legenda tipo de estudo](https://user-images.githubusercontent.com/26144462/168658781-6bd3b935-6b0c-4091-88f9-a74e51854083.JPG)

**Comment by anakatiacamilo** [comment]
proposta de cores para legenda dos efeitos para nova aba que está sendo criada:
Positivo - verde bandeira
Potencial Positivo - verde claro
Negativo - vermelho
Potencial negativo - laranja
Sem efeito - Rosa claro
Misturado - Azul Bic
Não informado - Cinza

@veronicaabdala, o arqivo que eu trabalhei não tinha exatamente estas opções 
Positivo - verde bandeira
Potencial Positivo - verde claro
Não informado - Cinza
e a opção Inconclusico que deixei em amarelo

![image](https://user-images.githubusercontent.com/19270675/168813933-be81b1db-9030-4435-954b-afda5e413520.png)

Será que estou trabalhando com o arquivo Correto??

Quanto ao novo layout, não encontrei o conjunto de igual o da legenda proposta então deixe com as cores que estava, porque, achei parecida.

**Comment by veronicaabdala** [comment]
Sim, o arquivo está correto. Eu indiquei as cores para todas as opções do campo. E as células para grupo de intervenções e grupos de desfechos? Vc conseguiu mudar a cor?

**Comment by anakatiacamilo** [comment]
Atualizado https://public.tableau.com/app/profile/bireme/viz/sequelas-covid-pos-aguda-pt/evidence-map
