### ISSUE TITLE
Mapa de evidencias efetividade clínica Moxabustão

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#325]
Envio o texto resumo sobre o mapa de evidência Moxabustão, já publicado. 
[Texto resumo mapa Moxabustão 10dez.docx](https://github.com/bireme/data-governance/files/7695021/Texto.resumo.mapa.Moxabustao.10dez.docx)

**Comment by veronicaabdala** [comment]
Incluir filtro população

**Comment by anakatiacamilo** [comment]
Atualizado
https://public.tableau.com/app/profile/bireme/viz/moxabustao-pt/evidence-map?publish=yes
