### ISSUE TITLE
teste - publicar mapa do Hospital do Coração no Tableau Public Bireme

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#327]
publicar mapa do Hospital do Coração no Tableau Public Bireme como teste. O mapa está disponi´vel em: https://public.tableau.com/app/profile/hcor/viz/shared/CTFZX6Z6T

**Comment by anakatiacamilo** [comment]
Segue o link do Mapa de Evidências publicado no Tableau da BIREME. 

https://public.tableau.com/app/profile/bireme/viz/MapadeEvidnciassobreEstratgiasparaPrevenoeTratamentodoExcessodePesoInfantil/Histria1

**Comment by anakatiacamilo** [comment]
@veronicaabdala a questão do link para a pesquisa da BVS 
Exemplo:
https://pesquisa.bvsalud.org/portal/resource/pt/biblio-1353633

E só trocar o ID com o prefixo no caso do exemplo **biblio-1353633**. 
Isso resolveria a questão?

**Comment by anakatiacamilo** [comment]
Conforme orientado este mapa de evidência foi excluido da publicação do tableau da BIREME
