### ISSUE TITLE
string para registro na BVS

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#328]
Por favor informar a string que leva o link para um registro na BVS a partir da informação do ID do registro.

**Comment by anakatiacamilo** [comment]
@veronicaabdala a questão do link para a pesquisa da BVS
Exemplo:
https://pesquisa.bvsalud.org/portal/resource/pt/biblio-1353633

E só trocar o ID com o prefixo no caso do exemplo biblio-1353633.
Isso resolveria a questão?
