### ISSUE TITLE
Mapa de Evidências Efetividade Clínica da Moxabustão

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#330]
Atualizar Mapa de Evidências Efetividade Clínica da Moxabustão de acordo com a planilha em anexo. Atualizar o texto sobre também

[Mapa Moxabustão_planilha_final_21jan22.xlsx](https://github.com/bireme/data-governance/files/7952767/Mapa.Moxabustao_planilha_final_21jan22.xlsx)
[Texto - SOBRE - Moxabustão - Versão 22.01.docx](https://github.com/bireme/data-governance/files/7952768/Texto.-.SOBRE.-.Moxabustao.-.Versao.22.01.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar. Segue o link
https://public.tableau.com/app/profile/bireme/viz/moxabustao-pt/dashboard

**Comment by anakatiacamilo** [comment]
Observação: No Filtro de País/Região Foco tem duas opções parecidas: "Não reportado" e "Não especificado"
