### ISSUE TITLE
Mapa de Evidências Efetividade Clínica da Ventosaterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#332]
Processar e publicar o mapa de evidências Efetividade Clínica da Ventosaterapia. O texto sobre ainda não está disponível.

[planilha_final_mapa_ventosa_21dez21.xlsx](https://github.com/bireme/data-governance/files/7952833/planilha_final_mapa_ventosa_21dez21.xlsx)

**Comment by anakatiacamilo** [comment]
Feito, por favor, verificar. Segue o link 
https://public.tableau.com/app/profile/bireme/viz/ventosaterapia-pt/evidence-map

**Comment by anakatiacamilo** [comment]
Observação: No Filtro de País/Região Foco tem duas opções parecidas: "Não reportado" e "Não especificado"

**Comment by anakatiacamilo** [comment]
Realizado e sem observação do usuário

**Comment by veronicaabdala** [comment]
por favor publicar o texto sobre e resumo para o mapa ventosaterapia
[Texto resumo mapaVentosa 9fev2022.docx](https://github.com/bireme/data-governance/files/8224675/Texto.resumo.mapaVentosa.9fev2022.docx)
[sobre_mapa_ventosa_fev22.docx](https://github.com/bireme/data-governance/files/8224676/sobre_mapa_ventosa_fev22.docx)

**Comment by anakatiacamilo** [comment]
Atualizado. Se precisar de ajuste, por favor, informar
