### ISSUE TITLE
Mapa de Evidências Efetividade Clínica da Homeopatia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#333]
Processar o Mapa de Evidências Efetividade Clínica da Homeopatia de acordo com a planilha em anexo. O texto sobre será elaboradao depois, a partir dos dados processados.

[Planilha_Final_mapa_homeopatia_processamento_27jan22.xlsx](https://github.com/bireme/data-governance/files/7953593/Planilha_Final_mapa_homeopatia_processamento_27jan22.xlsx)

**Comment by veronicaabdala** [comment]
Por favor considerar este arquivo
[Planilha_Final_mapa_homeopatia_processamento_27jan22.xlsx](https://github.com/bireme/data-governance/files/7953653/Planilha_Final_mapa_homeopatia_processamento_27jan22.xlsx)

**Comment by anakatiacamilo** [comment]
Feito, por favor, verificar. Segue o link https://public.tableau.com/app/profile/bireme/viz/homeopatia-pt/evidence-map

Observação: No Filtro de País/Região Foco tem duas opções parecidas: "Não reportado" e "Não especificado"

**Comment by veronicaabdala** [comment]
Por favor reprocessar o mapa de acordo com a planilha em anexo e considerar os seguintes ajustes:
1- Incluir o filtro População
2- Substituir o filtro "desenho dos estudos" (study design) pelo filtro "Desenho das revisões" (review design)
3- Apresentar o conteúdo do campo Interventions Group na vertical
4- Publicar na aba "Sobre" o conteúdo que segue no arquivo
5- Criar uma nova aba para o conteúdo "Resumo" com o conteúdo que segue no arquivo
[Planilha_Final_mapa_homeopatia_processamento_06fev2022.xlsx](https://github.com/bireme/data-governance/files/8015304/Planilha_Final_mapa_homeopatia_processamento_06fev2022.xlsx)
[sobre_mapa_homeopatia_fev2022.docx](https://github.com/bireme/data-governance/files/8015305/sobre_mapa_homeopatia_fev2022.docx)
[resumo mapa Homeopatia - 02fev 22.docx](https://github.com/bireme/data-governance/files/8015306/resumo.mapa.Homeopatia.-.02fev.22.docx)

**Comment by anakatiacamilo** [comment]
Mapa de Evidências Atualizado conforme a solicitação.
https://public.tableau.com/app/profile/bireme/viz/homeopatia-pt/evidence-map

**Comment by veronicaabdala** [comment]
Estou reenviando a planilha para reprocessamento porque esta inconsistência no campo país foco já havia sido corrigido e parece que não foram aplicados os dados desta planilha. Por favor considerar a planilha em anexo, com a data 8fev22. Também reenvio o texto resumo para harmonizar a fonte, que ficou meio estranho na publicação. 

[Planilha_Final_mapa_homeopatia_processamento_08fev2022.xlsx](https://github.com/bireme/data-governance/files/8026673/Planilha_Final_mapa_homeopatia_processamento_08fev2022.xlsx)
[resumo mapa Homeopatia - 8fev2022.docx](https://github.com/bireme/data-governance/files/8026674/resumo.mapa.Homeopatia.-.8fev2022.docx)

**Comment by veronicaabdala** [comment]
Estou reenviando a planilha para reprocessamento porque esta inconsistência no campo país foco já havia sido corrigido e parece que não foram aplicados os dados desta planilha. Por favor considerar a planilha em anexo, com a data 8fev22. Também reenvio o texto resumo para harmonizar a fonte, que ficou meio estranho na publicação.

[Planilha_Final_mapa_homeopatia_processamento_08fev2022.xlsx](https://github.com/bireme/data-governance/files/8026673/Planilha_Final_mapa_homeopatia_processamento_08fev2022.xlsx)
[resumo mapa Homeopatia - 8fev2022.docx](https://github.com/bireme/data-governance/files/8026674/resumo.mapa.Homeopatia.-.8fev2022.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala o Mapa atualizado, por favor, verificar

**Comment by veronicaabdala** [comment]
Sobre país foco, não encontrei na planilha a informação "não reportado" e no filtro população aparece uma opção NULL que eu não sei a que se refere

**Comment by anakatiacamilo** [comment]
Reprocessado ajustes para tirar o "não reportado" do filtro País/Região Foco e NULL do filtro População na etapa do Tableau Prep.

**Comment by veronicaabdala** [comment]
Por favor atualizar o texto resumo e sobre do mapa de evidencias efetividade clínica da homeopatia.

[resumo mapa Homeopatia - 25ago22.docx](https://github.com/bireme/data-governance/files/9427684/resumo.mapa.Homeopatia.-.25ago22.docx)
[sobre mapa Homeopatia - 25ago22.docx](https://github.com/bireme/data-governance/files/9427685/sobre.mapa.Homeopatia.-.25ago22.docx)
