### ISSUE TITLE
Mapa de Evidências - Plantas Medicinais Brasileiras

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#335]
Por favor processar o mapa de evidências - Plantas Medicinais Brasileiras a partir da planilha em anexo. Notas importantes:
1- A informação que vai como popup nas bolhas deve ser tomada do campo "Type of Review"
2- Os seguintes campos devem ser considerados como filtros: Effects, Population, Focus Country, Review Design e Type of Review
3- O campo Population, as ocorrências estão separadas com ponto e vírgula, gerar o filtro com os dados separados (similar ao processo feito para Focus Country)
4- Gerar o mapa como 3 abas: aba principal é o mapa propriamente dito e leva o nome "Mapa de Evidência"; uma aba para "Resumo dos Resultados" e outra aba para "Sobre este Mapa"
4.1 o conteúdo do resumo e do sobre enviarei em separado, não está feito ainda

5. No campo Detalhes - do Tableau, apresentar o nome do Mapa por extenso (fica na parte inferior, canto esquerdo, após a área do mapa)
6. Apresentar o conteúdo do campo Interventions Group na vertical
7. Apresentar o conteúdo do campo outcomes na vertical 

[planilha_mapa_plantas_BR_final_3mar2022.xlsx](https://github.com/bireme/data-governance/files/8180544/planilha_mapa_plantas_BR_final_3mar2022.xlsx)

**Comment by anakatiacamilo** [comment]
Feito, por favor, verificar

https://public.tableau.com/app/profile/bireme/viz/PlantasMedicinaisBrasileiras/evidence-map?publish=yes

**Comment by veronicaabdala** [comment]
Kátia, por favor republicar o mapa de evidências plantas brasileiras. Foram incluídos 4 novos estudos e segue a planilha atualizada. Também segue o texto resumo dos resultados e o texto sobre.
[planilha_mapa_plantas_BR_final_4maio22.xlsx](https://github.com/bireme/data-governance/files/8632436/planilha_mapa_plantas_BR_final_4maio22.xlsx)
[resumo mapa Plantas BR 4maio2022.docx](https://github.com/bireme/data-governance/files/8632437/resumo.mapa.Plantas.BR.4maio2022.docx)
[sobre mapa Plantas BR 4maio2022.docx](https://github.com/bireme/data-governance/files/8632438/sobre.mapa.Plantas.BR.4maio2022.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, fiz a atualização do Mapa de Evidências e só aumentaram 3 registros de 210 foi para 213 será que o arquivo esta correto? Ainda não publiquei.

**Comment by veronicaabdala** [comment]
Vou revisar agora

**Comment by veronicaabdala** [comment]
[planilha_mapa_plantas_BR_final_19maio22.xlsx](https://github.com/bireme/data-governance/files/8734450/planilha_mapa_plantas_BR_final_19maio22.xlsx)
Encontrei um erro no código de uma intervenção. Corrigi.

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/PlantasMedicinaisBrasileiras/evidence-map
