### ISSUE TITLE
Mapa de Evidências - Mortalidade Materna

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#336]
Segue nova planilha para atualizaçaõ do mapa de evidencias mortalidade materna - https://public.tableau.com/app/profile/bireme/viz/mortalidade-materna-pt/evidence-map

**Comment by veronicaabdala** [comment]
[Caracterizacao_Mapa_Mortalidade_Materna_processamento_7MAR2022.xlsx](https://github.com/bireme/data-governance/files/8216820/Caracterizacao_Mapa_Mortalidade_Materna_processamento_7MAR2022.xlsx)
[Sobre Mapa de Evidências Redução da Mortalidade Materna.docx](https://github.com/bireme/data-governance/files/8216821/Sobre.Mapa.de.Evidencias.Reducao.da.Mortalidade.Materna.docx)
[Resumo do mapa_mortalidade_materna_7mar2022.docx](https://github.com/bireme/data-governance/files/8216822/Resumo.do.mapa_mortalidade_materna_7mar2022.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar

**Comment by anakatiacamilo** [comment]
Lembrando que este Mapa de Evidência foi publicado no dia 15 de abril de 2021. E agora reprocessado com o novo formato.

Segue o novo link com o nome do mapa por extenso. 

5 - No campo Detalhes - do Tableau, apresentar o nome do Mapa por extenso (fica na parte inferior, canto esquerdo, após a área do mapa)
https://public.tableau.com/app/profile/bireme/viz/ReduodaMortalidadeMaterna/evidence-map

1- A informação que vai como popup nas bolhas deve ser tomada do campo 
"Type of Review" and "Publication Country" E uma tabela com linha e coluna por isto tem o Publication Country também.

2- Os seguintes campos devem ser considerados como filtros: 
Effects, 
Population, 
Focus Country, 
Review Design,
Type of Review e 
**Study Design** 
- Inclui o Study Design, 
- os filtros que tinham o conteúdo "Nulo" foram substituidos por "Não Informado"
- o filtro País/Região Foco foram agrupados os conteúdos solicitados: Áustria e Emirados Árabes Unidos;
- o filtro Efeitos foi agrupado: Potencial **P**ositivo e alterado o Potencial **N**egativo;
Por favor, verificar a tradução dos títulos dos filtros e quais filtros devem ficar no Mapa.

3- O campo Population, as ocorrências estão separadas com ponto e vírgula, gerar o filtro com os dados separados (similar ao processo feito para Focus Country)
- O mesmo foi feito com o campo Study Design;

4- Gerar o mapa como 3 abas: aba principal é o mapa propriamente dito e leva o nome "Mapa de Evidência"; uma aba para "Resumo dos Resultados" e outra aba para "Sobre este Mapa".

6 - Apresentar o conteúdo do campo Interventions Group na vertical
7 - Apresentar o conteúdo do campo outcomes na vertical
