### ISSUE TITLE
Mapa de evidências - Benefícios da atividade física para a saúde da população

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#337]
Por favor processar o mapa  de evidências - Benefícios da atividade física para a saúde da população, de acordo com a planilha em anexo. Também o texto sobre e o resumo, para ser publicado nas abas do mapa.
[Mapa_AF_ajustado_bireme_9mar.xlsx](https://github.com/bireme/data-governance/files/8217319/Mapa_AF_ajustado_bireme_9mar.xlsx)
[Resumo_mapa_atividade_fisica.docx](https://github.com/bireme/data-governance/files/8217322/Resumo_mapa_atividade_fisica.docx)
[Sobre_mapa_atividade_fisica.docx](https://github.com/bireme/data-governance/files/8217323/Sobre_mapa_atividade_fisica.docx)

**Comment by veronicaabdala** [comment]
por favor considerar este arquivo do sobre
[Sobre_mapa_atividade_fisica_revisado.docx](https://github.com/bireme/data-governance/files/8217611/Sobre_mapa_atividade_fisica_revisado.docx)

**Comment by anakatiacamilo** [comment]
Mapa disponível 

https://public.tableau.com/app/profile/bireme/viz/Benefciosdaatividadefsicaparaasadedapopulao/evidence-map

Este mapa demorou para ser processado, porque:
- no arquivo "Mapa_AF_ajustado_bireme_9mar.xlsx" a ordem das colunas na planinha RS estava trocado a ondem correta é a seguinte: Number / Title / Interventions Group / Interventions /Outcomes Group / Outcomes / Effects / Population / Database / Id / Confidence Level / Type of Review / Study Design / Review Design / Focus Country / Publication Country / Publication Year / Full Text / Citation
- no mesmo arquivo na planilha Interventions o nome das colunas são: Intervention**s** Group / Code / Interventions 

Para este processamento arrumei o arquivo enviado, mas se ele tiver que ser reprocessado, por favor, corrigir antes de enviar.

==>> Quanto o filtro País/Região Foco:
É uma duvida esta região esta correta ou foi um erro de escrita? **Australásia**
Agrupei 
  Estados Unidos +  Estados Unidos da America = Estados Unidos
  Portugal + Portugual = Portugal 
  Suiça + Suíça = Suiça + Suíça

Por favor, verificar.

**Comment by veronicaabdala** [comment]
Por favor, republicar o mapa de acordo com a planilha em anexo, houve uma correção em duas linhas da planilha. obrigada, 
[Mapa_AF_ajustado_bireme_6abr.xlsx](https://github.com/bireme/data-governance/files/8430123/Mapa_AF_ajustado_bireme_6abr.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, assim como o primeiro arquivo , este arquivo de atualização não esta no padrão combinado, por favor, corrigir o arquivo na origem seguindo as orientações que esta no comentario acima.
