### ISSUE TITLE
Mapa de Evidências sobre Meditação e Mindfulness 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#338]
Por favor atualizar o Mapa de Evidências sobre Meditação e Mindfulness de acordo com a planilha em anexo, atualizar o texto resumo e criar a aba para o texto sobre, seguindo o modelo dos últimos mapas. Em especial:

- O conteúdo do campo Outcomes apresentar na vertical;
- O campo Review Type é o que deve estar relacionado nas bolhas
- Não considerar o campo Study Design como filtro, este campo est[a vazio na planilha

[Sobre do mapa_Meditação_SES_SP_v2_17mar22.docx](https://github.com/bireme/data-governance/files/8292845/Sobre.do.mapa_Meditacao_SES_SP_v2_17mar22.docx)
[Resumo do mapa_Meditação_SES_SP_v2_17mar22.docx](https://github.com/bireme/data-governance/files/8292846/Resumo.do.mapa_Meditacao_SES_SP_v2_17mar22.docx)
[mapa_meditação_SES_SP_17mar22.xlsx](https://github.com/bireme/data-governance/files/8292860/mapa_meditacao_SES_SP_17mar22.xlsx)

**Comment by anakatiacamilo** [comment]
- O campo Review Type é o que deve estar relacionado nas bolhas: a bolha e uma tabela com linha e coluna: então substitui o Study Design por type of Review e mantive o Publication Country (agrupei Grã-Bretanha com Reuino Unido).
 - Não considerar o campo Study Design como filtro, este campo est[a vazio na planilha. OK
 - O conteúdo do campo Outcomes apresentar na vertical. OK

No documento de resumo e sobre a informação abaixo aparece nos dois documentos.

_"Grupo de trabalho responsável pela elaboração do Mapa

Aline Ângela Victoria Ribeiro; Bruna Carolina de Araújo; Cézar Donizetti Luquine Júnior; 
Cintia de Freitas Oliveira; Daiane Sousa Melo; Laís de Moura Milhomens; Laura dos Santos Boeira; Letícia Aparecida Lopes Bezerra da Silva; Marcio Sussumu Hirayama; Maritsa Carla de Bortoli; Roberta Crevelário de Melo; Rosana Samir Derbas Mustapha; Taís Rodrigues Tesser; Tereza Setsuko Toma; 

Coordenador: Jorge Otávio Maia Barreto

Colaboração: Instituto de Saúde de São Paulo, Fiocruz Brasília e Instituto Veredas.

Como citar:

Instituto de Saúde de São Paulo; Fiocruz Brasília; Instituto Veredas. Mapa de Evidências sobre Meditação e Mindfulness [Online]. São Paulo: BIREME/OPAS/OMS. Março 2021."_


Mapa atualizado conforme solicitação.
https://public.tableau.com/app/profile/bireme/viz/meditacao-mindfulness-pt/evidence-map

**Comment by anakatiacamilo** [comment]
Inclui o filtro População e Denhenho de Revisão
Atualizei os nomes das abas "Resumo dos Resultados"  "Sobre este Mapa"

No campo Detalhes - do Tableau, apresentar o nome do Mapa por extenso (fica na parte inferior, canto esquerdo, após a área do mapa)

Segue o novo link com o nome atualizado solicitado pela @veronicaabdala  

https://public.tableau.com/app/profile/bireme/viz/MeditaoeMindfulness/evidence-map?publish=yes
