### ISSUE TITLE
Padronização de encoding dos bancos MySQL 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/data-governance#34]
Todos servidores bancos de dados MySQL devem estar configurados para criação por padrão de bases usando collation **utf8_unicode_ci** e tabelas charset **utf8**.

**Comment by viniciusandrade** [comment]
Comando a serem aplicados para conversão:

ALTER SCHEMA `fi_admin`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_unicode_ci ;

ALTER TABLE table_name CONVERT TO CHARACTER SET utf8;

**Comment by viniciusandrade** [comment]
Configuração do arquivo my.cnf 

[mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
character-set-server = utf8

Referência: https://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf

**Comment by josemarcello** [comment]
Boa tarde Pessoal

Ainda estão me mantendo em copia no e-mail.



Atenciosamente,

[cid:7AA98DC088C04265AE3B8952FD981266]
Em 8 de fev de 2019 14:33 -0200, viniciusandrade <notifications@github.com>, escreveu:

Comando a serem aplicados para conversão:

ALTER SCHEMA fi_admin DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci ;

ALTER TABLE table_name CONVERT TO CHARACTER SET utf8;

**Comment by viniciusandrade** [comment]
@josemarcello 

Você esta recebendo cópia porque ainda esta associado ao projeto. 

Você irá realizar mais alguma atualização de arquivos no projeto?

Abraços

**Comment by viniciusandrade** [comment]
Ajustes realizados nos ambientes de teste e produção do banco de dados.
