### ISSUE TITLE
Mapa de Evidências “Aplicação Clínica da Ozonioterapia no Tratamento da COVID-19”

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#340]
Solicito atualização do Mapa de Evidências “Aplicação Clínica da Ozonioterapia no Tratamento da COVID-19”, versão em inglês e português. 
[mapa ozonioterapia covid-19_atualizado 1abril22.xlsx](https://github.com/bireme/data-governance/files/8398273/mapa.ozonioterapia.covid-19_atualizado.1abril22.xlsx)
[resumo_mapa_evidencias_ozonio_covid_ingles_1abril22.docx](https://github.com/bireme/data-governance/files/8398274/resumo_mapa_evidencias_ozonio_covid_ingles_1abril22.docx)
[resumo_mapa_evidencias_ozonio_covid_Port_1abril22.docx](https://github.com/bireme/data-governance/files/8398275/resumo_mapa_evidencias_ozonio_covid_Port_1abril22.docx)

**Comment by veronicaabdala** [comment]
Considerar os seguintes arquivos para o resumo em inglês e português, e o sobre também em inglês e português

[about_mapa_evidencias_ozonio_covid_ingles_1abril22.docx](https://github.com/bireme/data-governance/files/8398323/about_mapa_evidencias_ozonio_covid_ingles_1abril22.docx)
[resumo_mapa_evidencias_ozonio_covid_ingles_1abril22.docx](https://github.com/bireme/data-governance/files/8398324/resumo_mapa_evidencias_ozonio_covid_ingles_1abril22.docx)
[resumo_mapa_evidencias_ozonio_covid_Port_1abril22.docx](https://github.com/bireme/data-governance/files/8398325/resumo_mapa_evidencias_ozonio_covid_Port_1abril22.docx)
[sobre_mapa_evidencias_ozonio_covid_Port_1abril22.docx](https://github.com/bireme/data-governance/files/8398326/sobre_mapa_evidencias_ozonio_covid_Port_1abril22.docx)

**Comment by anakatiacamilo** [comment]
1- A informação que vai como popup nas bolhas deve ser tomada do campo
"Study Design" and "Publication Country" E uma tabela com linha e coluna por isto tem o Publication Country também e o campo "Type of Review" é Nulo.

2- Os seguintes campos devem ser considerados como filtros:
Effects==>> Nulo,
Population,
Focus Country,
Review Design,
Type of Review ==>> Nulo e
Study Design

4- Gerar o mapa como 3 abas: aba principal é o mapa propriamente dito e leva o nome "Mapa de Evidência"; uma aba para "Resumo dos Resultados" e outra aba para "Sobre este Mapa".
5- No campo Detalhes - do Tableau, apresentar o nome do Mapa por extenso (fica na parte inferior, canto esquerdo, após a área do mapa)
6- Apresentar o conteúdo do campo Interventions Group na vertical
7- Apresentar o conteúdo do campo outcomes na vertical

Novos Links 
https://public.tableau.com/app/profile/bireme/viz/AplicaoClnicadaOzonioterapianoTratamentodaCOVID-19/evidence-map?publish=yes

https://public.tableau.com/app/profile/bireme/viz/OzonetherapyfortreatmentofCOVID-19/evidence-map?publish=yes

**Comment by veronicaabdala** [comment]
Katia, o mapa em inglês não mostra os termos interventions, outcomes, e dos filtros em inglês, de acordo com a planilha. Reenviando a planilha
[mapa.ozonioterapia.covid-19_atualizado_ingles_29mar22.xlsx](https://github.com/bireme/data-governance/files/8457198/mapa.ozonioterapia.covid-19_atualizado_ingles_29mar22.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, Atualizei os Mapas de Evidências.

https://public.tableau.com/app/profile/bireme/viz/AplicaoClnicadaOzonioterapianoTratamentodaCOVID-19/evidence-map?publish=yes

https://public.tableau.com/app/profile/bireme/viz/OzonetherapyfortreatmentofCOVID-19/evidence-map?publish=yes

Observação o Outcomes Group do Code D1 esta diferente nas versões em português e inglês.
