### ISSUE TITLE
Sobre - Mapa de Evidências Sequelas da COVID-19 Pós-Aguda 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#342]
Por favor, é possível incluir um link para o informe completo do Mapa de Evidências Sequelas da COVID-19 Pós-Aguda que já está publicado? O link pode ir solto em algum lugar do mapa ou dentro do texto sobre. Envio o arquivo do texto sobre com o link para o informe completo, que está em:  https://docs.bvsalud.org/biblioref/2022/05/1366821/mapa-de-evidencias-covid-sequelas-relatorio-completo-30mar22.pdf

[sobre_mapa_sequelas_covid_10dez.docx](https://github.com/bireme/data-governance/files/8871686/sobre_mapa_sequelas_covid_10dez.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, tive que fazer ajustes no tamanho da letra. Por favor, verificar.
