### ISSUE TITLE
Ajustes no mapa de evidências Aromaterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#343]
Reenvio a planilha do mapa de aromaterapia para reprocessamento, pois houve algumas correções. Reenvio também o texto resumo.

Solicito ainda ajuste no campo "review design" como indicado na imagem em anexo. E mover o posicionamento do nome do grupo de intervenções para o início da célula, como mostrado na imagem que segue.
![ajuste mapa aroma](https://user-images.githubusercontent.com/26144462/173154290-457e29be-6f8c-4fd9-b9e8-82c5e67fc744.JPG)
[Planilha_Mapa_Aromaterapia_final_07jun22.xlsx](https://github.com/bireme/data-governance/files/8882416/Planilha_Mapa_Aromaterapia_final_07jun22.xlsx)
[Resumo_Mapa Aromaterapia_09junho2022_ajustado.docx](https://github.com/bireme/data-governance/files/8882417/Resumo_Mapa.Aromaterapia_09junho2022_ajustado.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar.
