### ISSUE TITLE
Mapa de evidências Terapias Complementares e Integrativas para Câncer do Útero

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#344]
Por favor processar e publicar o Mapa de evidências Terapias Complementares e Integrativas para Câncer do Útero. Considerar como filtros para o mapa os campos: Efeitos (coluna G), População (coluna H), desenho dos estudos (columa M), desenho das revisões (coluna N), país/região foco (coluna O).

Gerar o mapa com 4 abas:
Mapa de Evidências (por nível de confiança) - considerar como variáveis intervenções-desfechos-nível de confiança-tipo de revisão
Mapa de Evidências (por efeitos) -  considerar como variáveis intervenções-desfechos-efeito-tipo de revisão  (seguindo o modelo do mapa Aromaterapia)
Resumo
Sobre

[Mapa_Cancer_Caracterizacao_Revisões_13jun22.xlsx](https://github.com/bireme/data-governance/files/8891973/Mapa_Cancer_Caracterizacao_Revisoes_13jun22.xlsx)
[resumo_principais_achados_mapa_evidencia_cancer 13jun22.docx](https://github.com/bireme/data-governance/files/8891974/resumo_principais_achados_mapa_evidencia_cancer.13jun22.docx)
[sobre_mapa_cancer_13jun22.docx](https://github.com/bireme/data-governance/files/8891975/sobre_mapa_cancer_13jun22.docx)

**Comment by veronicaabdala** [comment]
Por favor considerar este arquivo para a aba "resumo" 
[resumo_principais_achados_mapa_evidencia_cancer 15jun22.docx](https://github.com/bireme/data-governance/files/8911944/resumo_principais_achados_mapa_evidencia_cancer.15jun22.docx)

**Comment by anakatiacamilo** [comment]
Publicado, por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/cancer-utero-pt/evidence-map

**Comment by anakatiacamilo** [comment]
Alterações solicitadas pela Veronica

1- Centraliza o texto no Navegador da História 
![image](https://user-images.githubusercontent.com/19270675/178732131-15e51f9c-3ce1-49b4-b2dd-46206c204a03.png)

Resposta: No Tableau não tem o alinhamento para o texto neste objeto.

2- o nome completo do mapa
Duvida: Posso colocar o nome completo sem acento, mas isto vai alterar a URL do mapa de evidência. Tudo bem?

3-   Alterar o nome do filtro para Efeito da Intervenção
Resposta: Alterado

4- ajuste nos espaços, negrito em algumas partes
Duvida: o que exatamente devo fazer apagar os espaços e tirar o negrito?

Conforme conversamos vamos fazer uma reunião para ajustar estes problemas e eu vou mostrar como altera-los no tableau
