### ISSUE TITLE
Evidence Map - Clinical Effectiveness of Medical Ozone Therapy

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#345]
Por favor atualizar o Mapa de Evidências - Clinical Effectiveness of Medical Ozone Therapy #285, versão inglês, de acordo com a planilha em anexo. 
Criar aba - Main Findings (arquivo em anexo)
Na aba About - usar o arquivo em anexo
Considerar os seguintes filtros: Focus Country (coluna O), Study Design (Coluna M), Review Design (Coluna N), Effects (coluna G).
Atenção: o quadro que aparece em cada bolha deve mostrar o número de revisões (Type of Review - coluna L), como indicado na imagem em anexo.

![image](https://user-images.githubusercontent.com/26144462/173664973-849cc2ae-316e-4c63-966d-5be5d953baf4.png) 
![ajuste mapa ozonio](https://user-images.githubusercontent.com/26144462/173665020-be655573-fe24-4784-b5b6-7d595d401225.JPG)

[about mapa ozonioterapia_ingles_9jun22.docx](https://github.com/bireme/data-governance/files/8902915/about.mapa.ozonioterapia_ingles_9jun22.docx)
[Main_findings_mapa_ozonioterapia_ingles_9jun22.docx](https://github.com/bireme/data-governance/files/8902916/Main_findings_mapa_ozonioterapia_ingles_9jun22.docx)
[Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles.xlsx](https://github.com/bireme/data-governance/files/8902936/Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles.xlsx)

**Comment by veronicaabdala** [comment]
[Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles.xlsx](https://github.com/bireme/data-governance/files/8904112/Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles.xlsx)
 Por favor considerar esta planilha, fiz uma pequena correção em um termo

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar principalmente as opções do Study Design.
