### ISSUE TITLE
Mapa de Evidência - Efetividade Clínica da Ozonioterapia Médica 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#346]
Por favor atualizar o mapa Mapa de Evidência - Efetividade Clínica da Ozonioterapia Médica - versão português, considerando os mesmas sugestões que fiz para o mapa em inglês, em relação aos filtros, abas e associação na bolha.
[Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_portugues.xlsx](https://github.com/bireme/data-governance/files/8904144/Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_portugues.xlsx)
[resumo mapa ozonioterapia_pt_9jun22.docx](https://github.com/bireme/data-governance/files/8904145/resumo.mapa.ozonioterapia_pt_9jun22.docx)
[sobre mapa ozonioterapia_pt_9jun22.docx](https://github.com/bireme/data-governance/files/8904146/sobre.mapa.ozonioterapia_pt_9jun22.docx)
![ajuste mapa ozonio](https://user-images.githubusercontent.com/26144462/173695736-57f6c436-364a-4228-a502-37064748d292.JPG)

https://public.tableau.com/app/profile/bireme/viz/ozonioterapia-pt/evidence-map

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar.
