### ISSUE TITLE
Mapa de evidências Terapias Complementares e Integrativas para Dor Crônica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#347]
Por favor publicar o Mapa de evidências Terapias Complementares e Integrativas para Dor Crônica de acordo com a planilha em anexo. Observações:
a) Considerar como filtros os campos: Efeitos (coluna G), População (coluna H), desenho dos estudos (columa M), desenho das revisões (coluna N), país/região foco (coluna O).
b) Gerar o mapa com 4 abas:
- Mapa de Evidências (por nível de confiança) - considerar como variáveis intervenções-desfechos-nível de confiança-tipo de revisão
- Mapa de Evidências (por efeitos) - considerar como variáveis intervenções-desfechos-efeito-tipo de revisão (seguindo o modelo do mapa Aromaterapia)
- Resumo
- Sobre

[Mapa_Dor_Caracterizacao_Revisões_final_20jun22.xlsx](https://github.com/bireme/data-governance/files/8941595/Mapa_Dor_Caracterizacao_Revisoes_final_20jun22.xlsx)
[sobre_mapa_dor_20jun22.docx](https://github.com/bireme/data-governance/files/8941596/sobre_mapa_dor_20jun22.docx)
[Texto resumo mapa dor 20jun22.docx](https://github.com/bireme/data-governance/files/8941597/Texto.resumo.mapa.dor.20jun22.docx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar 
https://public.tableau.com/app/profile/bireme/viz/Mapa_de_Evidencias_Terapias_Complementares_e_Integrativas_para_Dor_Cronica/evidence-map

**Comment by veronicaabdala** [comment]
ok, parece correto. Vou pedir para o GT revisar. obrigada,
