### ISSUE TITLE
Mapa de Evidências - Plantas Medicinais Brasileiras #335

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#349]
Por favor reprocessar o Mapa de Evidências - Plantas Medicinais Brasileiras #335, fiz uma correção em um outcome que estava com o nome errado (H29 - Transtornos de ansiedade).

[planilha_mapa_plantas_BR_final_13jul22.xlsx](https://github.com/bireme/data-governance/files/9101892/planilha_mapa_plantas_BR_final_13jul22.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado

**Comment by veronicaabdala** [comment]
ok, correto.obrigada
