### ISSUE TITLE
Mapa de evidências aromaterapia - atualizar

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#350]
Por favor atualizar o mapa de evidências Aromaterapia #343, foi feita uma correção em 2 outcomes. 

[Planilha_Mapa_Aromaterapia_final_30jun22.xlsx](https://github.com/bireme/data-governance/files/9101963/Planilha_Mapa_Aromaterapia_final_30jun22.xlsx)

**Comment by veronicaabdala** [comment]
e também precisa atualizar o resumo
[Resumo_Mapa Aromaterapia_13jul22.docx](https://github.com/bireme/data-governance/files/9101994/Resumo_Mapa.Aromaterapia_13jul22.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar!!

**Comment by veronicaabdala** [comment]
ok, obrigada. correto

**Comment by anakatiacamilo** [comment]
Alterado

**Comment by veronicaabdala** [comment]
perfeito. obrigada
