### ISSUE TITLE
Mapa de Evidências efetividade da profilaxia pós-exposição à hanseníase

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#351]
Por favor processar o  Mapa de Evidências efetividade da profilaxia pós-exposição à hanseníase de acordo com a planilha em anexo. 

Como título curto: ProfilaxiaHanseniase

Criar visualizações: Mapa de evidências (por nível de confiança); Mapa de evidências (por efeito da intervenção); Resumo; e Sobre 

Seguir modelo do mapa aromaterapia, com cor para a coluna grupo de intervenção e  linha do grupo de desfecho. 

[hanseniase_profilaxia_Caracterizacao_Evidencias_final_5ago22.xlsx](https://github.com/bireme/data-governance/files/9269417/hanseniase_profilaxia_Caracterizacao_Evidencias_final_5ago22.xlsx)
[resumo mapa profilaxia hanseníase 5ago22.docx](https://github.com/bireme/data-governance/files/9269418/resumo.mapa.profilaxia.hanseniase.5ago22.docx)
[sobre mapa profilaxia hanseniase 5ago22.docx](https://github.com/bireme/data-governance/files/9269419/sobre.mapa.profilaxia.hanseniase.5ago22.docx)

**Comment by anakatiacamilo** [comment]
Por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/ProfilaxiaHanseniase/evidence-map
