### ISSUE TITLE
Mapa de evidencias - efetividade clínica da homeopatia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#353]
Por favor atualizar o texto resumo e sobre do mapa de evidencias efetividade clínica da homeopatia.

[resumo mapa Homeopatia - 25ago22.docx](https://github.com/bireme/data-governance/files/9427684/resumo.mapa.Homeopatia.-.25ago22.docx)
[sobre mapa Homeopatia - 25ago22.docx](https://github.com/bireme/data-governance/files/9427685/sobre.mapa.Homeopatia.-.25ago22.docx)

**Comment by veronicaabdala** [comment]
Por favor considerar a versão destes arquivos:

[resumo mapa Homeopatia - 28ago22.docx](https://github.com/bireme/data-governance/files/9440523/resumo.mapa.Homeopatia.-.28ago22.docx)
[sobre mapa Homeopatia - 25ago22.docx](https://github.com/bireme/data-governance/files/9440524/sobre.mapa.Homeopatia.-.25ago22.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/homeopatia-pt/evidence-map
