### ISSUE TITLE
Mapa de Evidencias Aromaterapia - versão atualizada setembro 2022

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#354]
Solicito por favor a publicação no Tableau Public Bireme da versão atualizada do Mapa de Evidências Aromaterapia, que está disponível em: https://public.tableau.com/app/profile/cabsin.br/viz/aromaterapia-ptatualizao/evidence-map

Por favor manter a primeira data de publicação (30 nov 2021) do mapa que está hoje publicado em https://public.tableau.com/app/profile/bireme/viz/aromaterapia-pt/evidence-map e agregar a data de atualização (22 setembro 2022)

![image](https://user-images.githubusercontent.com/26144462/191827743-2dc62a65-3962-4a08-9ffb-3e7ddf95fee2.png)

**Comment by veronicaabdala** [comment]
Este mapa foi possível carregar? Ou prefere que eu envie a planilha para refazer o processamento?

**Comment by anakatiacamilo** [comment]
planilha pra refazer o processamento

**Comment by anakatiacamilo** [comment]
O Filtro País/Região Foco está diferente nos Mapas então provavelmtente um esta desatualizado e no outro não esta normalizado. Se tiver a necessidade de ficar revisando o Mapa prefiro fazer. 

![image](https://user-images.githubusercontent.com/19270675/194388730-0c2d566e-f72c-48fb-b103-67f928aa0bbe.png)


![image](https://user-images.githubusercontent.com/19270675/194388520-60ff915b-d802-4f1a-a95d-240a9fbd273f.png)
