### ISSUE TITLE
mapa de evidências Plantas Medicinais Brasileiras

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#355]
Solicito o reprocessamento do mapa de evidências Plantas Medicinais Brasileiras, pois houve uma revisão e atualização dos dados. O mapa anterior está em https://public.tableau.com/app/profile/bireme/viz/PlantasMedicinaisBrasileiras/evidence-map 

Solicito criar uma nova aba para mostrar as associações por efeito - Mapa de Evidência (por efeito da intervenção) aplicando as seguintes cores para legenda:

Positivo - verde #33CC33
Potencial Positivo - verde claro #A2E8A2
Sem Efeito - rosa #F5B9F1
Inconclusivo - azul #4657F4
Não informado - cinza  #BEBEBE

Segue planilha de caracterização dos dados e texto para a aba Resumo dos resultados. 

[planilha_mapa_plantas_BR_reprocessar_20set22.xlsx](https://github.com/bireme/data-governance/files/9646309/planilha_mapa_plantas_BR_reprocessar_20set22.xlsx)
[resumo mapa Plantas BR 22set2022.docx](https://github.com/bireme/data-governance/files/9646346/resumo.mapa.Plantas.BR.22set2022.docx)

**Comment by anakatiacamilo** [comment]
Listo

**Comment by anakatiacamilo** [comment]
#f9d7e6 rosa
#f6f0a4 amarelo

#bef8e1 verde
#d6e5fa azul
