### ISSUE TITLE
Mapa de Evidências Avaliação de Políticas de Saúde

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#356]
Por favor, processar o mapa de evidências avaliação de políticas de saúde, conforme especificações:

Título do Mapa: Mapa de Evidências Avaliação de Políticas de Saúde
Nome para a URL: avaliacao-de-politicas

3 Abas do Mapa: 
Mapa de Evidências (por nível de confiança)
Principais Achados
Sobre o Mapa

4 Filtros:
População – campo de dado “Population”
Desenho dos Estudos – campo de dado “Study Design”
País/Região Foco – campo de dados “Focus Country”
Adequação do Método – campo de dados “Effects” 
     * Notar que o nome do filtro, no lugar de efeito da intervenção (usado em outros mapas)
     * Não vamos usar os campos "review design" e "study design" como filtros.

Para a parte gráfica do mapa, por favor considerar:
- Usar a cor #D8A27E na linha dos grupos de Desfechos, com nome do grupo em bold e centralizado nas células, e na horizontal.
- Usar a cor #C17039 na coluna dos grupos de Intervenções, com nome do grupo em bold e centralizado nas células e na vertical.
- Nome dos desfechos na vertical.
- Nome das intervenções na horizontal.

Sugestão de cor para as bolhas – nível de confiança:
Alto – cor verde #28E431
Moderado – cor azul #62D5E8
Baixo – cor amarela #F0DA56

[versao_limpa_caracterizacao mapa avaliaçao politicas 26set2022.xlsx](https://github.com/bireme/data-governance/files/9665980/versao_limpa_caracterizacao.mapa.avaliacao.politicas.26set2022.xlsx)
[resumo_principais_achados_mapa_politicas_saude_27SET22.docx](https://github.com/bireme/data-governance/files/9665982/resumo_principais_achados_mapa_politicas_saude_27SET22.docx)
[sobre_mapa_politicas.docx](https://github.com/bireme/data-governance/files/9665983/sobre_mapa_politicas.docx)

**Comment by anakatiacamilo** [comment]
Na coluna Focus Country:
França (42) e France(6)  - Agrupados em França
Holanda (54) e Países Baixos (18) - não agrupei necessito de instruções.

**Comment by veronicaabdala** [comment]
Obrigada pelo ajuste país França. Pode juntar Holanda com Países Baixos, preferindo Holanda (72)

**Comment by anakatiacamilo** [comment]
https://public.tableau.com/app/profile/bireme/viz/avaliacao-de-politicas/evidence-map

**Comment by veronicaabdala** [comment]
obrigada, já passei para a equipe revisar. Eu acho que está ok.
