### ISSUE TITLE
 - Mapa avaliação de pol[iticas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#357]
Por favor revisar a linha - grupo de desfechos do Mapa de evidências Avaliaçao de Pol[iticas de Saúde, conforme mostrado na figura que segue:

![image](https://user-images.githubusercontent.com/26144462/193692194-231015f9-644d-4d75-9ae9-d499f9a41fae.png)

**Comment by anakatiacamilo** [comment]
![image](https://user-images.githubusercontent.com/19270675/194142257-f2cdb2b9-3cd6-4528-8048-f01bcb4e4fc5.png)
@veronicaabdala, por favor, verificar testei no Edge e Chrome
