### ISSUE TITLE
Mapa de Evidências da Efetividade Clínica da Aromaterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#358]
Solicito o reprocessamento do Mapa de Evidências Aromaterapia, considerando:

Título: Mapa de Evidências da Efetividade Clínica da Aromaterapia
Manter o mesmo padrão aplicado para os grupos de desfechos, interventions, como está na versão anterior deste mapa em https://public.tableau.com/app/profile/bireme/viz/aromaterapia-pt/evidence-map

Atualizar o texto resumo 
[Resumo_Mapa Aromaterapia_19out22.docx](https://github.com/bireme/data-governance/files/9707477/Resumo_Mapa.Aromaterapia_19out22.docx)

[Planilha_Mapa_Aromaterapia_reprocessar_19set22.xlsx](https://github.com/bireme/data-governance/files/9707481/Planilha_Mapa_Aromaterapia_reprocessar_19set22.xlsx)

**Comment by anakatiacamilo** [comment]
Por favor, verificar
