### ISSUE TITLE
mapa de evidências Profilaxia Hanseníase

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#359]
Por favor reprocessar o mapa Profilaxia Hanseníase, houve uma atualização nos desfechos.
O mapa está publicado em: https://public.tableau.com/app/profile/bireme/viz/ProfilaxiaHanseniase/evidence-map 

Segue a planilha atualizada e o texto resumo.

obrigada

[hanseniase_profilaxia_Caracterizacao_Evidencias_final_13out22.xlsx](https://github.com/bireme/data-governance/files/9777755/hanseniase_profilaxia_Caracterizacao_Evidencias_final_13out22.xlsx)
[resumo mapa profilaxia hanseníase 13out22.docx](https://github.com/bireme/data-governance/files/9777756/resumo.mapa.profilaxia.hanseniase.13out22.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
