### ISSUE TITLE
Mapa de evidências – Efetividade de intervenções para a redução de acidentes de trânsito com motocicletas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#360]
Por favor processar e publicar o Mapa de evidências – Efetividade de intervenções para a redução de acidentes de trânsito com motocicletas, com 4 abas: Mapa de Evidência (por nível de confiança), Mapa de Evidência (por efeito da intervenção), Resumo, Sobre 

![image](https://user-images.githubusercontent.com/26144462/196225588-dbce1ba3-cca8-4a57-8a70-6de85661ba2e.png)

Aplicar os grupos de intervenções na vertical, e os desfechos na vertical. Por favor aplicar cor nas células dos grupos intervenções e desfechos.

Nome curto do mapa: acidentes_motocicletas
[Caracterizacao_Revisões_acidente_moto_para processamento 17out22.xlsx](https://github.com/bireme/data-governance/files/9802457/Caracterizacao_Revisoes_acidente_moto_para.processamento.17out22.xlsx)
[sobre_mapa_acidente_moto_29set.docx](https://github.com/bireme/data-governance/files/9802460/sobre_mapa_acidente_moto_29set.docx)
[resumo_mapa_evidencia_acidente_moto17out22.docx](https://github.com/bireme/data-governance/files/9802461/resumo_mapa_evidencia_acidente_moto17out22.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, poderia passar o link onde vão colocar este mapa de evidencia para tentar combinar as cores.

**Comment by veronicaabdala** [comment]
Será no Portal de Mapa de Evidências. Mas vou sugerir a cor para facilitar:
Grupo de desfechos - #BD9ED6
Grupo de intervenções - #0EC2FA

![cores](https://user-images.githubusercontent.com/26144462/196547714-384b8818-8a0b-4b07-8500-714692e804de.JPG)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar

https://public.tableau.com/app/profile/bireme/viz/acidentes_motocicletas-pt/evidence-map
