### ISSUE TITLE
Mapa de evidências Terapias Complementares e Integrativas para Doenças Cardiovasculares

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#361]
Por favor processar o mapa de evidências Terapias Complementares e Integrativas para Doenças Cardiovasculares, com as seguintes considerações:

Nome do mapa: Terapias Complementares e Integrativas para Doenças Cardiovasculares
Nome curto para a url: Doencas_Cardiovasculares

4 abas: Mapa de Evidência (por nível de confiança), Mapa de Evidência (por efeito da intervenção), Resumo, Sobre

Aplicar os grupos de intervenções na vertical, e os desfechos na vertical. Por favor aplicar cor nas células dos grupos intervenções e desfechos. Grupo de desfechos - #BD9ED6
Grupo de intervenções - #0EC2FA
[Texto resumo mapa dcv.docx](https://github.com/bireme/data-governance/files/9830412/Texto.resumo.mapa.dcv.docx)
[sobre_mapa_dcv.docx](https://github.com/bireme/data-governance/files/9830413/sobre_mapa_dcv.docx)
[Mapa_DCV_Caracterizacao_Revisões 9ago22.xlsx](https://github.com/bireme/data-governance/files/9830414/Mapa_DCV_Caracterizacao_Revisoes.9ago22.xlsx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/cardiovasculares-pt/evidence-map
