### ISSUE TITLE
Mapa de evidências Benefícios da atividade física para a saúde da população

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#362]
Por favor atualizar o dado Sobre e Resumo do mapa de evidências Estratégias para promover a saúde da população nos municípios, já publicado no tableau bireme em: 
https://public.tableau.com/app/profile/bireme/viz/Benefciosdaatividadefsicaparaasadedapopulao/evidence-map

Se possível mudar o título do mapa para: Estratégias para promover a saúde da população nos municípios

[Resumo_Promo_Saude_Tableau_8nov.docx](https://github.com/bireme/data-governance/files/9971580/Resumo_Promo_Saude_Tableau_8nov.docx)
[Sobre_mapa_atividade_fisica_revisado_9nov22.docx](https://github.com/bireme/data-governance/files/9971581/Sobre_mapa_atividade_fisica_revisado_9nov22.docx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/Benefciosdaatividadefsicaparaasadedapopulao/evidence-map
Observação: o nome foi trocado
