### ISSUE TITLE
Mapa de Evidências - Redução da Mortalidade Materna

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#363]
Por favor reprocessar e publicar nova versão do Mapa de Evidências - Redução da Mortalidade Materna, que foi atualizado pelo grupo de trabalho. 
- Incluir uma aba para "Mapa de Evidência (por efeito da intervenção)"
- A primeira aba com o nome "Mapa de Evidência (por nível de confiança)"
- Manter outcomes na vertical
- Manter grupo de desfechos na vertical
- Usar cor nas células dos grupos de outcomes (#C5E0B3 )  e grupos de intervenções ( #9CB6F8 ) 

[Processamento_Caracterizacao_Mapa_Mortalidade_Materna_15nov22.xlsx](https://github.com/bireme/data-governance/files/10021711/Processamento_Caracterizacao_Mapa_Mortalidade_Materna_15nov22.xlsx)
[Resumo site mapa_mortalidade_materna_15NOV22.docx](https://github.com/bireme/data-governance/files/10021714/Resumo.site.mapa_mortalidade_materna_15NOV22.docx)
[Sobre Mapa de Evidências Redução da Mortalidade Materna 15nov22.docx](https://github.com/bireme/data-governance/files/10021715/Sobre.Mapa.de.Evidencias.Reducao.da.Mortalidade.Materna.15nov22.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, Mapa de Evidêmcia atualizado, por favor, verificar.
O grupo de desfechos eu achei melhor a horizontal, se vc fizer questão que fique na vertical me avise.

**Comment by veronicaabdala** [comment]
[Processamento_Caracterizacao_Mapa_Mortalidade_Materna_16nov22.xlsx](https://github.com/bireme/data-governance/files/10024874/Processamento_Caracterizacao_Mapa_Mortalidade_Materna_16nov22.xlsx)
Será necessário reprocessar, tinha um erro na planilha - coluna Nível de confiança e na coluna tipo de revisão. Corrigi e segue nova planilha. Muito obrigada.

**Comment by anakatiacamilo** [comment]
Atualizado.
