### ISSUE TITLE
Evidence Map - Clinical Effectiveness of Moxibustion

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#366]
Por favor processar a versão em inglês do Evidence Map Clinical Effectiveness of Moxibustion, com base no mapa português publicado em https://public.tableau.com/app/profile/bireme/viz/moxabustao-pt/evidence-map

Título: Evidence Map - Clinical Effectiveness of Moxibustion
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/moxabustao-en/evidence-map

Labels em inglês a considerar:

Português	Inglês
BIREME/OPAS/OMS	BIREME/PAHO/WHO
Mapa de Evidência	Evidence Map
Sobre	About
Desenho dos Estudos	Type of Review
País/Região Foco	Focus Country/Region
Efeitos	Effect of intervention
População	Population
Revisões Selecionadas:	# Studies:
Desfechos	Outcomes
Intervenções	Interventions
Nível de Confiança 	 Confidence Level
Clique para acessas as evidências	 - Access to studies
País de Publicação	Publication country
Base de Dados	Database

Criar a aba Main Findings - doc en anexo

Aplicar cor na linha de Outcomes Group #B4E9FA
Aplicar cor na coluna de Interventions Group #AA99DB

Imagem para representar os labels traduzidos:
![image](https://user-images.githubusercontent.com/26144462/212122805-af8e844f-3ff0-40a8-8651-9c1bf7ec2f42.png)

Arquivos atachados:

Labels traduzidos ao inglês
Planilha de dados em inglês
Texto Main Findings
Texto About

[Mapa Moxabustão_planilha_final_21jan22_tradução_ingles.xlsx](https://github.com/bireme/data-governance/files/10403656/Mapa.Moxabustao_planilha_final_21jan22_traducao_ingles.xlsx)
[main_findings_mapa_moxabustion.docx](https://github.com/bireme/data-governance/files/10403660/main_findings_mapa_moxabustion.docx)
[About_mapa_moxibustion.docx](https://github.com/bireme/data-governance/files/10403674/About_mapa_moxibustion.docx)
[labels_mapa_traducao_ingles.docx](https://github.com/bireme/data-governance/files/10403677/labels_mapa_traducao_ingles.docx)

**Comment by anakatiacamilo** [comment]
Por favor, revisar
https://public.tableau.com/app/profile/bireme/viz/moxabustao-en/evidence-map?publish=yes
