### ISSUE TITLE
Mapa de Evidências Medicina Antroposófica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#367]
Por favor integrar este mapa no nosso Tableau.
Código:

<div class='tableauPlaceholder' id='viz1673473541758' style='position: relative'><noscript><a href='#'><img alt='Mapa de Evidência - Efetividade Clínica da MEDICINA ANTROPOSÓFICACABSIN ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;AN&#47;ANTROPOSOFIA&#47;evidence-map&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='ANTROPOSOFIA&#47;evidence-map' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;AN&#47;ANTROPOSOFIA&#47;evidence-map&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='pt-BR' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1673473541758');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1016px';vizElement.style.height='991px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>

**Comment by anakatiacamilo** [comment]
@veronicaabdala, com a infomação do issues não será possível.

**Comment by veronicaabdala** [comment]
ok, vou pedir os dados em planilha e ajustar ao nosso modelo. obrigada,
