### ISSUE TITLE
Mapa de evidências - Efetividade Clínica da Medicina Antroposófica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#368]
Por favor reprocessar e publicar o Mapa de Evidências - Efetividade Clínica da Medicina Antroposófica

Título: Mapa de Evidências Efetividade Clínica da Medicina Antroposófica

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-pt/evidence-map

Incluir 4 abas: Mapa de evidência (por nível de confiança); Mapa de evidência (por efeito da intervenção); Resumo; Sobre

Nas abas 1 e 2:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos (#C5E0B3 ) e grupos de intervenções ( #9CB6F8 )

Incluir os seguintes 4 filtros: Desfechos; Efeitos da intervenção; População; País/Região Foco
Nota: o filtro desfechos é novo deve ser gerado com dados da coluna "outcomes" na planilha RS

[Mapa Antroposofia_planilha_9fev23.xlsx](https://github.com/bireme/data-governance/files/10701643/Mapa.Antroposofia_planilha_9fev23.xlsx)
[Resumo mapa antroposofia.docx](https://github.com/bireme/data-governance/files/10701644/Resumo.mapa.antroposofia.docx)
[sobre mapa antroposofia.docx](https://github.com/bireme/data-governance/files/10701645/sobre.mapa.antroposofia.docx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-pt/evidence-map
