### ISSUE TITLE
Mapa de Evidencias Efectividad Clínica de la Apiterapia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#369]
Por favor processar a versão em espanhol do Mapa de Evidencias Efectividad Clínica de la Apiterapia, com base no mapa português publicado em https://public.tableau.com/app/profile/bireme/viz/apiterapia-pt/evidence-map  

Título: Mapa de Evidencias Efectividad Clínica de la Apiterapia 
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/apiterapia-es/evidence-map   

Labels en espanhol a considerar:
Português - Español
BIREME/OPAS/OMS - BIREME/OPS/OMS
Mapa de Evidência - Mapa de Evidencia
Sobre - Acerca
Desenho dos Estudos - Tipo de Revisión
País/Região Foco - País/Región Enfoque
Efeitos- Efecto de la Intervención
População - Población
Revisões Selecionadas: - # Revisiones:
Desfechos - Desenlaces
Intervenções - Intervenciones
Nível de Confiança - Nivel de Confianza
Clique para acessar as evidências - Acceso a los estudios
País de Publicação - País de publicación
Alto – Alto
Baixo – Bajo
Criticamente Baixo – Críticamente Bajo
Criar a aba Principales Hallazgos - doc en anexo
Aplicar cor na linha de Outcomes Group #B4E9FA
Aplicar cor na coluna de Interventions Group #AA99DB

![image](https://user-images.githubusercontent.com/26144462/220942024-8c4b35c3-8c84-4004-90ac-8da3ac43eced.png)
[acerca apiterapia.docx](https://github.com/bireme/data-governance/files/10814830/acerca.apiterapia.docx)
[mapa_apiterapia_traducao_espanhol 7fev.xlsx](https://github.com/bireme/data-governance/files/10814831/mapa_apiterapia_traducao_espanhol.7fev.xlsx)
[resumen mapa Apiterapia.docx](https://github.com/bireme/data-governance/files/10814832/resumen.mapa.Apiterapia.docx)

**Comment by anakatiacamilo** [comment]
Por favor, verificar o mapa se estiver bom vou usar como template de idioma.

**Comment by veronicaabdala** [comment]
Muito bom. indiquei uns pequenos ajustes no ppt que segue
![image](https://user-images.githubusercontent.com/26144462/221887903-06386707-4037-44fa-b415-a7f155e90f40.png)

![image](https://user-images.githubusercontent.com/26144462/221887951-2736ec27-eea4-4b9b-8485-7cb9af74f853.png)


[sugestões template mapa.pptx](https://github.com/bireme/data-governance/files/10851441/sugestoes.template.mapa.pptx)

**Comment by anakatiacamilo** [comment]
Fiz as alterações solicitadas, menos  a cor dos Efeitos que infelizmente não tem muitas opções de cores

![image](https://user-images.githubusercontent.com/19270675/222150178-37b06cbf-800d-40ad-aa34-efa0599de1e9.png)



![image](https://user-images.githubusercontent.com/19270675/222149227-475d65b5-a2ff-416e-bdbc-3e1bb2fcd757.png)
