### ISSUE TITLE
Revisar mapeamento dos campos XML iAHx que não estão presentes nos arquivos CSV

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/data-governance#37]
@viniciusandrade @botturam Por favor, revisem a planilha https://github.com/bireme/data-governance/blob/master/docs/campos-xml-nao-localizados-nos-csvs.xlsx que acabo de atualizar, propondo mapeamento daqueles campos XML iAHx que não estão presentes nos arquivos CSV, propondo a criação ou inclusão do mesmo em um CSV existente. Lembrar que os arquivos CSV vão virar, nesse primeiro momento, coleção no MongoDB.

**Comment by botturam** [comment]
concluído o mapeamento dos campos em questão.
