### ISSUE TITLE
 Evidence Map Clinical Effectiveness of Apitherapy

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#370]
Por favor processar a versão em inglês do Mapa de Evidencia Efetividade Clínica da Apiterapia, com base no mapa português publicado em https://public.tableau.com/app/profile/bireme/viz/apiterapia-pt/evidence-map  

Título: Evidence Map Clinical Effectiveness of Apitherapy

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/apiterapia-en/evidence-map   

Labels em inglês a considerar:
Português Inglês
BIREME/OPAS/OMS BIREME/PAHO/WHO
Mapa de Evidência - Evidence Map
Sobre - About
Desenho dos Estudos - Type of Review
País/Região Foco - Focus Country/Region
Efeitos - Effect of intervention
População - Population
Revisões Selecionadas:     # Studies:
Desfechos - Outcomes
Intervenções -  Interventions
Nível de Confiança - Confidence Level
Clique para acessar as evidências - Access to studies
País de Publicação - Publication country
Base de Dados - Database

Criar a aba Main Findings - doc en anexo

Aplicar cor na linha de Outcomes Group #B4E9FA
Aplicar cor na coluna de Interventions Group #AA99DB

Imagem para representar os labels traduzidos:
![image](https://user-images.githubusercontent.com/26144462/220945664-98879d3d-fe8d-4111-a746-7bcc5e65e65f.png)

[about apitherapy.docx](https://github.com/bireme/data-governance/files/10814947/about.apitherapy.docx)
[abstract map Apiterapia.docx](https://github.com/bireme/data-governance/files/10814948/abstract.map.Apiterapia.docx)
[Labels traduzidos apiterapia - ingles e espanhol.docx](https://github.com/bireme/data-governance/files/10814998/Labels.traduzidos.apiterapia.-.ingles.e.espanhol.docx)

[mapa_apiterapia_traducao_ingles_7fev.xlsx](https://github.com/bireme/data-governance/files/10814950/mapa_apiterapia_traducao_ingles_7fev.xlsx)

**Comment by veronicaabdala** [comment]
Faltou gerar a visualização por efeito da intervenção.

**Comment by anakatiacamilo** [comment]
No map-tooltip troquei o Type of Review por Review Design. E no sobre troquei a url [https://docs.bvsalud.org/biblioref/2022/12/1401877/efetividade-da-apiterapia-es.pdf](https://docs.bvsalud.org/biblioref/2022/12/1401877/efetividade-da-apiterapia.pdf) por https://docs.bvsalud.org/biblioref/2022/12/1401877/efetividade-da-apiterapia.pdf.

Por favor, verificar o mapa se estiver bom vou usar como template de idioma.
