### ISSUE TITLE
Mapa de Evidências Efetividade Clínica da Acupuntura

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#371]
Por favor reprocessar e publicar o Mapa de Evidências Efetividade Clínica da Acupuntura, que foi atualizado. Este mapa substitui o mapa publicado em https://public.tableau.com/app/profile/bireme/viz/acupuntura-pt/evidence-map 
Título: Mapa de Evidências Efetividade Clínica da Acupuntura
Manter a mesma URL: https://public.tableau.com/app/profile/bireme/viz/acupuntura-pt/evidence-map 
Incluir 4 abas: Mapa de evidência (por nível de confiança); Mapa de evidência (por efeito da intervenção); Resumo; Sobre
Nas abas 1 e 2:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos (#1766F5) e grupos de intervenções (#CB7117)
Incluir os seguintes 4 filtros: Desfechos; Efeitos da intervenção; População; País/Região Foco
Nota: o filtro desfechos é novo deve ser gerado com dados da coluna "outcomes" na planilha RS (semelhante ao criado para o mapa de medicina antroposófica).

[planilha_mapa_acupuntura_revisão_2023_final.xlsx](https://github.com/bireme/data-governance/files/10946219/planilha_mapa_acupuntura_revisao_2023_final.xlsx)
[Resumo mapa acupuntura 10 mar 2023.docx](https://github.com/bireme/data-governance/files/10946220/Resumo.mapa.acupuntura.10.mar.2023.docx)
[sobre mapa acupuntura março 2023.docx](https://github.com/bireme/data-governance/files/10946221/sobre.mapa.acupuntura.marco.2023.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, Mapa atualizado, por favor, verificar.

Duvida no mapa antigo tinha o filtro de "Tipo de Revisão" e "Desenho de Estudos" que foram substituidos pelos filtros de "Desfecho" e "População" o "Desenho de Estudos" foi para o pop-up com o "País de Publicação", mas o "Tipo de Revisão" foi retirado do Mapa. Estranhei, porque, no Resumo tem um destaque para esta informação.

Filtros Antigos
![image](https://user-images.githubusercontent.com/19270675/224720179-a1cc1b81-0a5b-48e6-9cee-dadd2cfa4cab.png)

A informação do Tipo de Revisão atualizada que não esta no mapa atual.
![image](https://user-images.githubusercontent.com/19270675/224725002-2c40707f-d994-49da-ad75-33ab714496ce.png)

Aba Mapa de evidência (por nível de confiança) com os filtros solicitados ==>> Incluir os seguintes 4 filtros: Desfechos; Efeitos da intervenção; População; País/Região Foco
![image](https://user-images.githubusercontent.com/19270675/224723242-bd217449-a260-412e-8f5b-24e96ec6e882.png)

Aba Mapa de evidência (por efeito da intervenção) com 3 dos filtros solicitados, troquei o Efeitos da intervenção pelo Nível de Confiança
![image](https://user-images.githubusercontent.com/19270675/224723459-6e64f45b-a46b-426d-8433-88afb581d37d.png)

Outra duvida e sobre a quantidade que diminuiu 7 revisões.

**Comment by veronicaabdala** [comment]
Oi Katia, este mapa foi todo revisado, completamente. Então o número diminuiu mesmo. Sobre os filtros, por favor mostar o campo tipo de revisão (type of review) dentro do mapa. E se possível, pode acrescentar o campo "study design" (desenho dos estudos) como filtro. 
![image](https://user-images.githubusercontent.com/26144462/224757015-5e316f70-b5d0-4121-855d-8734a6b09ed8.png)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar.
