### ISSUE TITLE
Mapa de Evidencias Acupuntura - uma correção

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#372]
Encontramos um erro em um estudo 11 e será necessário reprocessar para corrigir o mapa e o texto resumo. 
[Resumo mapa acupuntura 16 mar 2023.docx](https://github.com/bireme/data-governance/files/10992045/Resumo.mapa.acupuntura.16.mar.2023.docx)
[planilha_mapa_acupuntura_revisão_2023_final.xlsx](https://github.com/bireme/data-governance/files/10992046/planilha_mapa_acupuntura_revisao_2023_final.xlsx)

**Comment by veronicaabdala** [comment]
reenviando a planilha com correção do país de publicação

[planilha_mapa_acupuntura_revisão_2023_final.xlsx](https://github.com/bireme/data-governance/files/10992386/planilha_mapa_acupuntura_revisao_2023_final.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
