### ISSUE TITLE
Mapa de evidências - Efetividade Clínica da Medicina Antroposófica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#373]
Por favor atualizar o Mapa de evidências - Efetividade Clínica da Medicina Antroposófica, foi feita uma correção pelo grupo de trabalho.

Manter no mesmo link. Segue a planilha e o texto resumo dos principais achados. Muito obrigada, 

[Mapa Antroposofia_planilha_29MAR23.xlsx](https://github.com/bireme/data-governance/files/11099756/Mapa.Antroposofia_planilha_29MAR23.xlsx)
[Resumo mapa antroposofia 29MAR.docx](https://github.com/bireme/data-governance/files/11099757/Resumo.mapa.antroposofia.29MAR.docx)

**Comment by anakatiacamilo** [comment]
Mapa de Evidência Atualizado, por favor, verificar

@veronicaabdala, na coluna País/Região Foco tem o país "Países Baixos" e na coluna País de Publicação esta como Holanda.


![WhatsApp Image 2023-04-03 at 10 27 37](https://user-images.githubusercontent.com/19270675/229523922-5e7586c3-1737-4957-9c0d-bd05396fb858.jpeg)

**Comment by veronicaabdala** [comment]
Bem observado. Vamos passar para Holanda, normalizar. Vc arruma? e eu arrumo na planilha final aqui comigo. obrigada,

**Comment by anakatiacamilo** [comment]
@veronicaabdala, no FI-ADMIN está com o Países Baixos. Posso normalizar aqui só aguardo a definição de qual nome vamos usar.

![image](https://user-images.githubusercontent.com/19270675/230103071-db285d47-c0c2-440f-b021-ded6e2128bc0.png)

**Comment by anakatiacamilo** [comment]
Alterar, por favor, verificar
