### ISSUE TITLE
Evidence Map - Clinical Effectiveness of Anthroposophic Medicine

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#374]
Por favor gerar o mapa de evidencias Clinical Effectiveness of Anthroposophic Medicine, versão em inglês, usando os mesmos parâmetros do mapa em português. A url deve ser https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-en/evidence-map 

[Mapa Antroposofia_planilha_29MAR23_inglês.xlsx](https://github.com/bireme/data-governance/files/11603136/Mapa.Antroposofia_planilha_29MAR23_ingles.xlsx)
[Resumo mapa antroposofia ingles.docx](https://github.com/bireme/data-governance/files/11603137/Resumo.mapa.antroposofia.ingles.docx)
[sobre mapa antroposofia ingles.docx](https://github.com/bireme/data-governance/files/11603138/sobre.mapa.antroposofia.ingles.docx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-en/evidence-map
