### ISSUE TITLE
Mapa de evidências - Benefícios da atividade física para a saúde da população

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#376]
Processar o mapa com as seguintes especificações:
Título do mapa: [Sobre_mapa_atividade_fisica_revisado_29jun23.docx](https://github.com/bireme/data-governance/files/11916369/Sobre_mapa_atividade_fisica_revisado_29jun23.docx)
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/atividade-fisica-pt/evidence-map
Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808
O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.
Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0
Aba 2: Mapa de evidências (por nível de confiança)

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Positivo - #2FBB2F
Sem efeito - #B2B2B2
Aba 4: Resumo (principais achados)
Aba 5: Sobre
Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8
Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco
[Resumo_Atividade_Fisica_mapa_29jun23.docx](https://github.com/bireme/data-governance/files/11916370/Resumo_Atividade_Fisica_mapa_29jun23.docx)
[Mapa_AF_30mar22_final_31out22_ajustado_26jun23_processamento.xlsx](https://github.com/bireme/data-governance/files/11916371/Mapa_AF_30mar22_final_31out22_ajustado_26jun23_processamento.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, tinha um mapa de evidência com este nome que foi alterado para Estratégias para promover a saúde da população nos municípios segue a sua solicitação 
https://github.com/bireme/data-governance/issues/364 

Gostaria de saber se este Mapa de Evidência de agora e atualização do outro ou eh um mapa novo?

**Comment by veronicaabdala** [comment]
Oi Ana, são mapas diferentes Enviado do meu iPhoneEm 10 de jul. de 2023, à(s) 21:50, anakatiacamilo ***@***.***> escreveu:﻿
@veronicaabdala, tinha um mapa de evidência com este nome que foi alterado para Estratégias para promover a saúde da população nos municípios segue a sua solicitação
#364
Gostaria de saber se este Mapa de Evidência de agora e atualização do outro ou eh um mapa novo?

**Comment by anakatiacamilo** [comment]
Por favor, verificar

https://public.tableau.com/app/profile/bireme/viz/atividade-fisica-pt/evidence-map
