### ISSUE TITLE
Mapa de evidências Doença de Chagas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#377]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidências Doença de Chagas: diagnóstico, tratamento e análise de risco
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/doenca-chagas-pt/evidence-map
Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808
O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.
Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0
Aba 2: Mapa de evidências (por nível de confiança)
Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção:
Inconclusivo - #F57BDB
Positivo - #008000
Potencial Positivo - #B2DE82 
Não se aplica - #B2B2B2
Sem efeito - #0099FF

Aba 4: Resumo (principais achados)
[resumo_mapa_evidencia_chagas.docx](https://github.com/bireme/data-governance/files/12166351/resumo_mapa_evidencia_chagas.docx)

Aba 5: Sobre
[sobre_mapa_evidencia_chagas.docx](https://github.com/bireme/data-governance/files/12166350/sobre_mapa_evidencia_chagas.docx)

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical

Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8
Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco

[Caracterizacao_Revisões_Mapa_Doença_Chagas_versao_final_processamento.xlsx](https://github.com/bireme/data-governance/files/12166349/Caracterizacao_Revisoes_Mapa_Doenca_Chagas_versao_final_processamento.xlsx)

**Comment by anakatiacamilo** [comment]
Pronto, por favor, Verificar
https://public.tableau.com/app/profile/bireme/viz/doenca-chagas-pt/evidence-map
