### ISSUE TITLE
Mapa de Evidencias Efetividade Clínica da Auriculoterapia 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#378]
Processar o mapa com as seguintes especificações:

Título do mapa: Efetividade Clínica da Auriculoterapia 

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/auriculoterapia-pt/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Cores sugeridas para as bolhas:
Alto – verde #33CC33
Moderado – azul #00B0F0
Baixo – Amarelo #FFC000
Criticamente Baixo – Vermelho #C00000 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Positivo - #2FBB2F
Sem efeito - #B2B2B2

Aba 4: Resumo (principais achados)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco

[mapa_auriculoterapia_atualizacao_ago2023 .xlsx](https://github.com/bireme/data-governance/files/12402956/mapa_auriculoterapia_atualizacao_ago2023.xlsx)
[resumo_mapa_auriculoterapia_ago2023.docx](https://github.com/bireme/data-governance/files/12402958/resumo_mapa_auriculoterapia_ago2023.docx)
[sobre_mapa_auriculoterapia_ago2023.docx](https://github.com/bireme/data-governance/files/12402961/sobre_mapa_auriculoterapia_ago2023.docx)

**Comment by veronicaabdala** [comment]
considerar estes arquivos
[mapa_auriculoterapia_atualizacao_ago2023_portugues.xlsx](https://github.com/bireme/data-governance/files/12411176/mapa_auriculoterapia_atualizacao_ago2023_portugues.xlsx)
[resumo_mapa_auriculoterapia_ago2023_port.docx](https://github.com/bireme/data-governance/files/12411177/resumo_mapa_auriculoterapia_ago2023_port.docx)

**Comment by veronicaabdala** [comment]
Desculpas, encontramos mais um erro no documento resumo. Por favor considerar a versão do arquivo em anexo. 
[resumo_mapa_auriculoterapia_ago2023_port.docx](https://github.com/bireme/data-governance/files/12420432/resumo_mapa_auriculoterapia_ago2023_port.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, não atualizei os mapas de auriculoterapia, porque tem um erro nos IDS 32, 43 e 45 no código do outcome, por favor, revisar  

![image](https://github.com/bireme/data-governance/assets/19270675/a17d616e-72de-4054-8cf6-64a2a469ae80)

![image](https://github.com/bireme/data-governance/assets/19270675/47cc7ad1-a5d6-42ab-908a-1eb95d3e671b)

![image](https://github.com/bireme/data-governance/assets/19270675/d941fb5b-de80-4141-9d82-f9090f3febce)
