### ISSUE TITLE
Mapa de evidencias Auriculoterapia em ingles

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#379]
Processar o mapa com as seguintes especificações:

Título do mapa: Clinical Effectiveness of Auriculotherapy 

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/auriculoterapia-ent/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Evidence Map (General)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0

Aba 2: Evidence Map (by Confidence Level)
Cores sugeridas para as bolhas:
High – verde #33CC33
Moderate – azul #00B0F0
Low – Amarelo #FFC000
Critically Low – Vermelho #C00000 

Aba 3: Evidence Map (by Intervention Effect)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusive - #F57BDB
Negative - #FF0000
Positive - #2FBB2F
Potential Positive - #A2F8DF
No Effect - #B2B2B2

Aba 4: Summary (Key Findings)

Aba 5: About

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal – nome Outcomes
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4 filtros: Outcomes (dados da coluna “outcomes”); Intervention Effects; Population; Country/Region Focus
[sobre_mapa_auriculoterapia_ago2023_ingles.docx](https://github.com/bireme/data-governance/files/12420826/sobre_mapa_auriculoterapia_ago2023_ingles.docx)
[resumo_mapa_auriculoterapia_ago2023_ingles.docx](https://github.com/bireme/data-governance/files/12420827/resumo_mapa_auriculoterapia_ago2023_ingles.docx)
[mapa_auriculoterapia_atualizacao_ago2023_ingles.xlsx](https://github.com/bireme/data-governance/files/12420828/mapa_auriculoterapia_atualizacao_ago2023_ingles.xlsx)

**Comment by veronicaabdala** [comment]
Por favor considerar esta planilha, haviam alguns dados sem tradução. Desculpa

[mapa_auriculoterapia_atualizacao_ago2023_ingles_v2.xlsx](https://github.com/bireme/data-governance/files/12423326/mapa_auriculoterapia_atualizacao_ago2023_ingles_v2.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/auriculoterapia-en/evidence-map
