### ISSUE TITLE
Mapa de evidencias Auriculoterapia em espanhol

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#380]
Título do mapa: Efectividad Clínica de la Auriculoterapia 

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/auriculoterapia-es/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidencias (general)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0

Aba 2: Mapa de evidências (por nivel de confianza)
Cores sugeridas para as bolhas:
Alto – verde #33CC33
Moderado – azul #00B0F0
Bajo – Amarelo #FFC000
Críticamente Bajo – Vermelho #C00000 

Aba 3: Mapa de evidencia (por efecto de la intervención)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efecto de la intervención
Inconclusivo - #F57BDB
Negativo - #FF0000
Positivo - #2FBB2F
Potencial Positivo - #A2F8DF
Sem efeito - #B2B2B2

Aba 4: Resumen (principales hallazgos)

Aba 5: Acerca

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical – label “Desenlaces”
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4 filtros: Desenlaces (dados da coluna “outcomes”); Efecto de la intervención; Población; País/Región Foco
[sobre_mapa_auriculoterapia_ago2023_espanhol.docx](https://github.com/bireme/data-governance/files/12420840/sobre_mapa_auriculoterapia_ago2023_espanhol.docx)
[resumo_mapa_auriculoterapia_ago2023_esp.docx](https://github.com/bireme/data-governance/files/12420841/resumo_mapa_auriculoterapia_ago2023_esp.docx)
[mapa_auriculoterapia_atualizacao_ago2023_espanol.xlsx](https://github.com/bireme/data-governance/files/12420842/mapa_auriculoterapia_atualizacao_ago2023_espanol.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/auriculoterapia-es/evidence-map
