### ISSUE TITLE
Mapa de Evidencias Ozonioterapia Médica

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#381]
Reprocessar o mapa com as seguintes especificações:

Título do mapa: Ozonioterapia Médica
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/ozonioterapia-pt/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)

Cores sugeridas para as bolhas:
Alto – verde #33CC33
Moderado – azul #00B0F0
Baixo – Amarelo #FFC000
Criticamente Baixo – Vermelho #C00000 

Aba 3: Mapa de evidência (por efeito da intervenção)

Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Positivo - #2FBB2F
Potencial Positivo - #A2F8DF
Sem efeito - #B2B2B2

Aba 4: Resumo (principais achados)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; País/Região Foco; Desenho dos estudos
[Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_portugues_24ago.xlsx](https://github.com/bireme/data-governance/files/12443033/Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_portugues_24ago.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado.
https://public.tableau.com/app/profile/bireme/viz/ozonioterapia-pt/evidence-map

O Total mudou para 26.
A lista de títulos esta vinculada ao link e os números 4, 5, 7, 9 não tem link na tabela por isto na lista só tem 22 títulos
