### ISSUE TITLE
Mapa de Evidencias Ozonioterapia versão inglês

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#382]
Reprocessar o mapa com as seguintes especificações:

Título do mapa: Medical Ozone Therapy

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/ozonioterapia-en/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #FFA74F para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Evidence Map (General)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor azul #00B0F0

Aba 2: Evidence Map (by Confidence Level)
Cores sugeridas para as bolhas:
High – verde #33CC33
Moderate – azul #00B0F0
Low – Amarelo #FFC000
Critically Low – Vermelho #C00000 

Aba 3: Evidence Map (by Intervention Effect)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusive - #F57BDB
Negative - #FF0000
Positive - #2FBB2F
Potential Positive - #A2F8DF
No Effect - #B2B2B2

Aba 4: Summary (Key Findings)

Aba 5: About

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal – nome Outcomes
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4 filtros: Outcomes (dados da coluna “outcomes”); Intervention Effects; Study Design; Country/Region Focus
[Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles_25ago23.xlsx](https://github.com/bireme/data-governance/files/12443063/Mapa_evidencias_ozonioterapia_processamento_final_20maio2022_ingles_25ago23.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala o arquivo atualizado esta com o mesmo problema do português estão faltando 4 links dos ids 4, 5, ,7 e 9 vamos publicar assim mesmo?
