### ISSUE TITLE
Mapa de evidências Teleodontologia

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#383]
Processar o mapa com as seguintes especificações:
Título do mapa: Mapa de evidências - Teleodontologia
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/teleodontologia/evidence-map

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial Negativo - #A70111
Positivo - #1F7B1F
Potencial Positivo - #A2E8A2
Sem efeito - #00B0F0
Não informado – #4C5E6C
Não se aplica - #0E1A8C

Aba 4: Resumo (principais achados)

Aba 5: Sobre (o arquivo do sobre será enviado posteriormente)

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco
[Caracterizacao_Revisões_Mapa_Teleodonto_13set23.xlsx](https://github.com/bireme/data-governance/files/12621951/Caracterizacao_Revisoes_Mapa_Teleodonto_13set23.xlsx)
[Resumo EGM Teleodonto.docx](https://github.com/bireme/data-governance/files/12621952/Resumo.EGM.Teleodonto.docx)

**Comment by veronicaabdala** [comment]
[sobre_mapa_evidencia_teleodonto.docx](https://github.com/bireme/data-governance/files/12621984/sobre_mapa_evidencia_teleodonto.docx)
enviando o arquivo texto sobre

**Comment by veronicaabdala** [comment]
considerar esta planilha - fiz um ajuste 
[Caracterizacao_Revisões_Mapa_Teleodonto_15set23.xlsx](https://github.com/bireme/data-governance/files/12622298/Caracterizacao_Revisoes_Mapa_Teleodonto_15set23.xlsx)

**Comment by anakatiacamilo** [comment]
Feito, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/teleodontologia-pt/evidence-map

**Comment by veronicaabdala** [comment]
Tem algumas correções a fazer, reenvio a planilha, o texto sobre e o texto resumo ajustados.
![image](https://github.com/bireme/data-governance/assets/26144462/2834cfcb-b405-4c52-9860-0e522aa55af1)

![image](https://github.com/bireme/data-governance/assets/26144462/711683e4-08bf-44c1-9b18-970af32c8c54)

![image](https://github.com/bireme/data-governance/assets/26144462/6527a145-14e0-47f5-b4aa-92b5de33ad78)

[Caracterizacao_Revisões_Mapa_Teleodonto_16set23_portugues.xlsx](https://github.com/bireme/data-governance/files/12640407/Caracterizacao_Revisoes_Mapa_Teleodonto_16set23_portugues.xlsx)
[Resumo EGM Teleodonto_16set_portugues.docx](https://github.com/bireme/data-governance/files/12640409/Resumo.EGM.Teleodonto_16set_portugues.docx)
[sobre_mapa_evidencia_teleodonto_16set23_portugues.docx](https://github.com/bireme/data-governance/files/12640410/sobre_mapa_evidencia_teleodonto_16set23_portugues.docx)
[correçoes mapa teleodonto.pptx](https://github.com/bireme/data-governance/files/12640411/correcoes.mapa.teleodonto.pptx)

**Comment by anakatiacamilo** [comment]
Fiz os ajustes solicitados, mas não consigo atualizar os dados o arquivo excel não sei se as linhas dos documentos abaixo estão ocultos ou foram apagados.
O Resume e o Sobre consegui atualizar.

8	Accuracy and effectiveness of teledentistry: a systematic review of systematic reviews.
22	Can mHealth promotion for parents help to improve their children's oral health? A systematic review.
35	Effectiveness of E-Learning in Oral Radiology Education: A Systematic Review
38	Effectiveness of Virtual Reality Glasses as a Distraction for Children During Dental Care.
49	Online eLearning for undergraduates in health professions: A systematic review of the impact on knowledge, skills, attitudes and satisfaction.
53	Patient satisfaction with e-oral health care in rural and remote settings: a systematic review
59	Relevance of teleorthodontic tools: a systematic review of the literature / Pertinence des outils de téléorthodontie : une revue systématique de la littérature
69	Teledentistry and mHealth for Promotion and Prevention of Oral Health: A Systematic Review and Meta-analysis.
77	The feasibility of telehealth in the monitoring of head and neck cancer patients: a systematic review on remote technology, user adherence, user satisfaction, and quality of life.
78	The influence of mobile applications and social media-based interventions in producing behavior change among orthodontic patients: A systematic review and meta-analysis.
80	The scope of dental education during COVID-19 pandemic: A systematic review.

![image](https://github.com/bireme/data-governance/assets/19270675/3036d1d0-b69e-42ea-aebc-69b910c916fd)

**Comment by anakatiacamilo** [comment]
Consegui atualizar, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/teleodontologia-pt/evidence-map

**Comment by veronicaabdala** [comment]
Oi Kátia, estão faltando 2 estudos: 
Where Is the Artificial Intelligence Applied in Dentistry? Systematic Review and Literature Analysis.
A Systematic Review of Virtual Reality Therapeutics for Acute Pain Management.

Estou reenviando a planilha.
[Caracterizacao_Revisões_Mapa_Teleodonto_16set23_portugues.xlsx](https://github.com/bireme/data-governance/files/12665800/Caracterizacao_Revisoes_Mapa_Teleodonto_16set23_portugues.xlsx)

**Comment by veronicaabdala** [comment]
na versão em ingles tambem faltam 2 estudos

**Comment by anakatiacamilo** [comment]
@veronicaabdala, atualizei as versões em português e inglês, mas o total é de 44 registros. por favor, verificar as duas verões 
https://public.tableau.com/app/profile/bireme/viz/teleodontologia-pt/evidence-map
https://public.tableau.com/app/profile/bireme/viz/teleodontologia-en/evidence-map
