### ISSUE TITLE
Mapa de Evidencia Teleodontologia em inglês

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#384]
Processar o mapa Teleodontologia seguindo os mesmos parâmetros do mapa em português, mas na versão em inglês.

Título do Mapa:  Evidence Gap Map – Teledentistry

url https://public.tableau.com/app/profile/bireme/viz/teleodontologia-en/evidence-map
[About EGM Teledentistry 16sep23.docx](https://github.com/bireme/data-governance/files/12652038/About.EGM.Teledentistry.16sep23.docx)
[Ingles_Caracterizacao_Mapa_Teleodonto_18set23.xlsx](https://github.com/bireme/data-governance/files/12652039/Ingles_Caracterizacao_Mapa_Teleodonto_18set23.xlsx)
[Resumo Inglês_Evidence Gap Map_16set23.docx](https://github.com/bireme/data-governance/files/12652040/Resumo.Ingles_Evidence.Gap.Map_16set23.docx)

**Comment by anakatiacamilo** [comment]
Pronto, verificar
https://public.tableau.com/app/profile/bireme/viz/teleodontologia-en/evidence-map
