### ISSUE TITLE
Mapa de evidências - Arboviroses: estratégias de prevenção e controle

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#385]
Processar o mapa com as seguintes especificações:
Título do mapa: Mapa de evidências - Arboviroses: estratégias de prevenção e controle
URL sugerida: https://public.tableau.com/app/profile/bireme/viz/arboviroses-pt/evidence-map

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Positivo - #1F7B1F
Potencial Positivo - #A2E8A2
Sem efeito - #00B0F0
Não informado – #4C5E6C

Aba 4: Resumo (principais achados)

Aba 5: Sobre 

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Intervenções (dados da coluna interventions); População; País/Região Foco
[resumo_mapa_evidencia_arboviroses 21set23.docx](https://github.com/bireme/data-governance/files/12693412/resumo_mapa_evidencia_arboviroses.21set23.docx)
[sobre_mapa_evidencia_arboviroses 21set23.docx](https://github.com/bireme/data-governance/files/12693413/sobre_mapa_evidencia_arboviroses.21set23.docx)
[versao limpa Caracterizacao_Arboviroses 21set23.xlsx](https://github.com/bireme/data-governance/files/12693415/versao.limpa.Caracterizacao_Arboviroses.21set23.xlsx)

**Comment by anakatiacamilo** [comment]
![image](https://github.com/bireme/data-governance/assets/19270675/f30cebbe-10d1-4a61-a985-5f561643676f)

![image](https://github.com/bireme/data-governance/assets/19270675/d74697c4-2d1b-433b-b398-3aed60cdd44d)

**Comment by veronicaabdala** [comment]
Oi Ana Katia, conferi na planilha e são 47 estudos. Estou tentando analisar o problema pelos prints enviados, mas não estou entendendo.

**Comment by veronicaabdala** [comment]
Ah, entendi, tem dois estudos repetidos e com dados diferentes. Vou revisar a planilha. Por favor aguardar, vou corrigir e reenvio os arquivos

**Comment by veronicaabdala** [comment]
Reenviando a planilha e o texto resumo com os ajustes. agora são 45 estudos 

[versao limpa Caracterizacao_Arboviroses 27SET23.xlsx](https://github.com/bireme/data-governance/files/12738223/versao.limpa.Caracterizacao_Arboviroses.27SET23.xlsx)

[resumo_mapa_evidencia_arboviroses 27set23.docx](https://github.com/bireme/data-governance/files/12738225/resumo_mapa_evidencia_arboviroses.27set23.docx)

**Comment by veronicaabdala** [comment]
por favor considerar este resumo
[resumo_mapa_evidencia_arboviroses versao final_29 de setembro.docx](https://github.com/bireme/data-governance/files/12771301/resumo_mapa_evidencia_arboviroses.versao.final_29.de.setembro.docx)

**Comment by anakatiacamilo** [comment]
Feito, por favor, verificar.
https://public.tableau.com/app/profile/bireme/viz/arboviroses-pt/evidence-map
