### ISSUE TITLE
Mapa de evidências – Cannabis Medicinal

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#388]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidências sobre efetividade da Cannabis Medicinal

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/cannabis-medicinal-pt/evidence-map  
Sugestão de cores para eixos x e y:

Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #1F7B1F
Potencial positivo - #A2E8A2
Sem efeito - #00B0F0

Aba 4: Resumo (principais achados)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 5 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco; **Efeitos Adversos**

**Nota: efeitos adversos é um índice novo, primeira vez que foi usado em mapa e está na última coluna S da planilha**
[Cannabis_Caracterizacao_Revisões_21NOV23.xlsx](https://github.com/bireme/data-governance/files/13433020/Cannabis_Caracterizacao_Revisoes_21NOV23.xlsx)
[resumo_mapa_cannabis.docx](https://github.com/bireme/data-governance/files/13433021/resumo_mapa_cannabis.docx)
[sobre_mapa_cannabis.docx](https://github.com/bireme/data-governance/files/13433022/sobre_mapa_cannabis.docx)

**Comment by veronicaabdala** [comment]
[Cannabis_Caracterizacao_Revisões_21NOV23.xlsx](https://github.com/bireme/data-governance/files/13440825/Cannabis_Caracterizacao_Revisoes_21NOV23.xlsx)
 Reenviando a planilha, com uma correção. considerar esta versão

**Comment by anakatiacamilo** [comment]
@veronicaabdala, mapa pronto segue o link
https://public.tableau.com/app/profile/bireme/viz/cannabis-medicinal-pt/evidence-map

Fiz com a ultima planinha enviada hj. No resumo informa que foram incluidos 194 registros bibliograficos, mas o total do mapa tem 192 registros.
O Filtro Desfechos deixei conforme conversamos na reunião com o pessoal do MTCI, mas se precisar voltar para o filtro anterior e só avisar.

**Comment by veronicaabdala** [comment]
Desculpa, mas encontramos mais um erro na planilha, segue ajustada a planilha.
[Cannabis_Caracterizacao_Revisões_21NOV23_new.xlsx](https://github.com/bireme/data-governance/files/13444303/Cannabis_Caracterizacao_Revisoes_21NOV23_new.xlsx)

E deixamos os efeitos adversos para depois, não se preocupe

**Comment by veronicaabdala** [comment]
reenviando, considere esta planilha e resumo, por favor

[Cannabis_Caracterizacao_Revisões_23nov23.xlsx](https://github.com/bireme/data-governance/files/13445717/Cannabis_Caracterizacao_Revisoes_23nov23.xlsx)
[resumo_mapa_cannabis_23nov23.docx](https://github.com/bireme/data-governance/files/13445719/resumo_mapa_cannabis_23nov23.docx)

**Comment by veronicaabdala** [comment]
[Cannabis_Caracterizacao_Revisões_23nov23.xlsx](https://github.com/bireme/data-governance/files/13445823/Cannabis_Caracterizacao_Revisoes_23nov23.xlsx)
[sobre_mapa_cannabis.docx](https://github.com/bireme/data-governance/files/13445824/sobre_mapa_cannabis.docx)

Considera este arquivo. Corrigi a população de um estudo (2212)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, mapa atualizado, por favor, verificar

Eu já tinha colocado os 5 filtros que você tinha pedido inclusive o Efeitos Adversos.

![image](https://github.com/bireme/data-governance/assets/19270675/87907ddb-7d80-413d-a1a7-9c547bd232ac)
