### ISSUE TITLE
Mapa de evidências – Redução do Consumo de Bebidas Alcoólicas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#389]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidências – Redução do Consumo de Bebidas Alcoólicas

URL sugerida: <https://public.tableau.com/app/profile/bireme/viz/consumo-bebidas-alcoolicas-pt/evidence-map>  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.
Aba 1: Mapa de evidências (geral)

Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #1F7B1F
Potencial positivo - #A2E8A2
Sem efeito - #00B0F0

Aba 4: Resumo (principais achados)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8
Intervenções com 3 níveis, expor o grupo maior na vertical e os outros dois níveis na horizontal

Incluir os seguintes 5 filtros: Desfechos (dados da coluna “outcomes”); Intervenções (dados da coluna “inerventions”) Efeitos da intervenção; População; País/Região Foco; Efeitos Adversos

[Resumo_mapa_alcool.docx](https://github.com/bireme/data-governance/files/13500889/Resumo_mapa_alcool.docx)
[sobre_mapa_consumo_bebidas_alcoolicas.docx](https://github.com/bireme/data-governance/files/13500890/sobre_mapa_consumo_bebidas_alcoolicas.docx)
[Mapa_bebidas_alcoólicas_24nov23-v2.xlsx](https://github.com/bireme/data-governance/files/13500936/Mapa_bebidas_alcoolicas_24nov23-v2.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, normalmente o Number é igual a Title, mas desde mapa esta diferente

![image](https://github.com/bireme/data-governance/assets/19270675/0f4f8ce6-bfbf-47a7-a64b-5d49c6273e53)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar. Consegui ajustar melhor o tamanho tb.

**Comment by anakatiacamilo** [comment]
atualizado, por favor, verificar.

**Comment by veronicaabdala** [comment]
Kátia, está faltando o estudo 23, são 182 estudos e no mapa estão 181. O título que está faltando é "Alcohol, calories, and obesity ..." 
Aproveitei e fiz correções no campo País de Foco nos estudos 93 e 67

E verificar o que está acontecendo no estudo 136, também país de foco, que não considerou os países individuais, no índice aparece tudo junto: Tailândia; Brasil; Inglaterra; ...
[Mapa_bebidas_alcoólicas_24nov23-v3.xlsx](https://github.com/bireme/data-governance/files/13636343/Mapa_bebidas_alcoolicas_24nov23-v3.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, esta ultima versão do resumo tem 182 estudos, mas como eu disse no meu outro comentario os números 149 e 176 tem o mesmo título, mas com quantidades de linhas diferentes então aguardo orientação.

![image](https://github.com/bireme/data-governance/assets/19270675/3807b913-b597-4a86-a81d-5803a78d7917)

**Comment by veronicaabdala** [comment]
[Mapa_bebidas_alcoólicas_24nov23-v3.xlsx](https://github.com/bireme/data-governance/files/13639533/Mapa_bebidas_alcoolicas_24nov23-v3.xlsx)

**Comment by veronicaabdala** [comment]
reenviando a planilha, a anterior não constou a correção nos titulos estudos 149 e 176
[Mapa_bebidas_alcoólicas_24nov23-v4.xlsx](https://github.com/bireme/data-governance/files/13651876/Mapa_bebidas_alcoolicas_24nov23-v4.xlsx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, acho que descobri, porque o número 23 não aparece no mapa, a Interventions dele é B1.3 e este código não tem na aba Interventions, mas aparece  duas vezes o códigos B1.2.

![image](https://github.com/bireme/data-governance/assets/19270675/6382219e-e341-4907-9dfe-288ce635dd0b)


![image](https://github.com/bireme/data-governance/assets/19270675/45b54273-14fd-4395-92c1-28c75d72d827)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, alterei e atualizei o mapa, por favor, verificar
