### ISSUE TITLE
Evidence Map on effectiveness of Medicinal Cannabis

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#391]
Processar o mapa com as seguintes especificações:
Título do mapa: Evidence Map on effectiveness of Medicinal Cannabis

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/cannabis-medicinal-en/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Evidence Map (general)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Evidence Map (confidence level)
High – bolha cor verde #17A11A
Low – bolha cor azul #00B0F0
Critically Low – bolha cor vermelho #FF0000
Moderade – bolha cor laranja #FFA74F

Aba 3: Evidence Map (effect of the intervention)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusive - #F57BDB
Negative - #FF0000
Potential negative - #FFA74F
Positive - #1F7B1F
Potential positive - #A2E8A2
No effect - #00B0F0

Aba 4: Key Findings

Aba 5: About

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 5 filtros: Outcomes (dados da coluna “outcomes”); Effect of interventions; Population; Country Foccus; Adverse Effects

Nota: efeitos adversos é um índice novo, primeira vez que foi usado em mapa e está na última coluna S da planilha
[Cannabis_Caracterizacao_Revisões_23nov23_ingles.xlsx](https://github.com/bireme/data-governance/files/13512861/Cannabis_Caracterizacao_Revisoes_23nov23_ingles.xlsx)
[resumo_mapa_cannabis_ingles.docx](https://github.com/bireme/data-governance/files/13512863/resumo_mapa_cannabis_ingles.docx)
[sobre_mapa_cannabis-ingles.docx](https://github.com/bireme/data-governance/files/13512864/sobre_mapa_cannabis-ingles.docx)

**Comment by anakatiacamilo** [comment]
Por favor, verificar

https://public.tableau.com/app/profile/bireme/viz/cannabis-medicinal-en/evidence-map
