### ISSUE TITLE
Evidence map of Clinical Effectiveness of Bioenergetic Analysis 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#392]
Processar o mapa com as seguintes especificações:
Título do mapa: Evidence map of Clinical Effectiveness of Bioenergetic Analysis 
URL sugerida: <https://public.tableau.com/app/profile/bireme/viz/analise-bionergetica-en/evidence-map>  
Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808
O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.
Aba 1: Evidence Map (general)

Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0
Aba 2: Evidence Map (by methodological quality) – no lugar do nome Nível de Confiança

Very strong – bolha cor verde #17A11A
Strong – bolha cor azul #00B0F0
Very weak – bolha cor vermelho #FF0000
Weak – bolha cor laranja #FFA74F
Moderate – bolha cor rosa #FF66FF
Critically low – bolha cor cinza #FFFFFF 

Aba 3: Evidence Map (by effect of the interventions)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #1F7B1F
Potencial positivo - #A2E8A2
Sem efeito - #00B0F0

Aba 4: Key Findings
Aba 5: About
Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
[About the Evidence map of Clinical Effectiveness of Bioenergetic Analysis.docx](https://github.com/bireme/data-governance/files/13889602/About.the.Evidence.map.of.Clinical.Effectiveness.of.Bioenergetic.Analysis.docx)
[Characterization_bionergetic_map_27dez23.xlsx](https://github.com/bireme/data-governance/files/13889604/Characterization_bionergetic_map_27dez23.xlsx)
[key findings bionergetica.docx](https://github.com/bireme/data-governance/files/13889605/key.findings.bionergetica.docx)

Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8
Incluir os seguintes 5 filtros: Outcomes (dados da coluna “outcomes”); Interventions (dados da coluna “interventions”), Effect of the interventions; Population; Focus Country/Region

**Comment by anakatiacamilo** [comment]
Por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/analise-bionergetica-pt/evidence-map
