### ISSUE TITLE
Mapa de Evidências sobre intervenções para Redução do Consumo de Bebidas Alcoólicas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#393]
Por favor atualizar o texto sobre deste mapa

[Uploading sobre_mapa_consumo_bebidas_alcoolicas_23jan24.docx…]()

**Comment by anakatiacamilo** [comment]
@veronicaabdala, não estou conseguindo ver o arquivo sobre o mapa, vc poderia mandar novamente?

**Comment by veronicaabdala** [comment]
é só esta mesmo, por enquanto. Eles solicitaram para gerar um novo índice, mas ainda precisa de ajustes no dado. Quando finalizado eu passo por aqui. abraço, obrigada
