### ISSUE TITLE
Mapa redução consumo bebidas alcóolicas

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#394]
Segue planilha deste mapa para geração de um filtro novo - Intervenções Estratégia SAFER, no lugar do filtro intervenções. 
[Uploading Mapa_bebidas_alcoólicas_30jan24_v5.xlsx…]()

**Comment by anakatiacamilo** [comment]
@veronicaabdala, não estou conseguindo fazer upload deste arquivo

**Comment by anakatiacamilo** [comment]
Concluido, por favor, verificar.
