### ISSUE TITLE
Mapa de evidências “Estratégias em Programas e Políticas de Alimentação e Nutrição” 

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#395]
processar e publicar o mapa com as seguintes especificações:

Título do mapa: Estratégias em Programas e Políticas de Alimentação e Nutrição” 

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/pnan-pt/evidence-map

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #6CBCEE com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #9C5BCD

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial Negativo - #A70111
Positivo - #1F7B1F
Potencial Positivo - #A2E8A2
Sem efeito - #00B0F0
Não informado – #4C5E6C
Não se aplica - #0E1A8C

Aba 4: Resumo (principais achados)

Aba 5: Sobre
Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #93E9D2  e grupos de intervenções #6CBCEE

Incluir os seguintes 4 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco

[Sobre_Mapa_PNAN.docx](https://github.com/bireme/data-governance/files/14129414/Sobre_Mapa_PNAN.docx)
[resumo_mapa_pnan.docx](https://github.com/bireme/data-governance/files/14129415/resumo_mapa_pnan.docx)
[Mapa_PNAN_final_2024 16.01.2024_c.xlsx](https://github.com/bireme/data-governance/files/14129416/Mapa_PNAN_final_2024.16.01.2024_c.xlsx)

**Comment by anakatiacamilo** [comment]
Mapa publicado, por favor, verificar. 
https://public.tableau.com/app/profile/bireme/viz/pnan-pt/evidence-map

@veronicaabdala, para este mapa tive que fazer algumas correções na planilha então envio para você caso tenha alguma alteração

[evidence-map2process.xlsx](https://github.com/bireme/data-governance/files/14179561/evidence-map2process.xlsx)
