### ISSUE TITLE
deletar mapa

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#396]
Este mapa pode ser deletado do Tableau

https://public.tableau.com/app/profile/cabsin.br/viz/aromaterapia-ptatualizao/evidence-map

**Comment by anakatiacamilo** [comment]
@veronicaabdala, este link https://public.tableau.com/app/profile/cabsin.br/viz/aromaterapia-ptatualizao/evidence-map é de uma mapa que não esta publicado no tableau da BIREME, esta no tableau do Consorcio Acadêmico Brasileiro de Saúde Integrativa - CABSIN então eu não tenho como apaga-lo.

![image](https://github.com/bireme/data-governance/assets/19270675/43ce8d61-b696-40d2-9df2-f37448c4aadb)

Na Bireme nos temos um Mapa de Evidências da Efetividade Clínica da Aromaterapia
https://public.tableau.com/app/profile/bireme/viz/aromaterapia-pt/evidence-map e outro de Mapa de Evidência - Efetividade Clínica da Medicina Antroposófica em português e inglês https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-pt/evidence-map - https://public.tableau.com/app/profile/bireme/viz/medicina-antroposofica-en/evidence-map. Se você quiser que eu apague qualquer um que estiver no tableau da Bireme eu consigo.
