### ISSUE TITLE
Mapa de evidencias teleodontologia - versão ingles - atualizada

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#397]
Processar o mapa com as seguintes especificações:

Título do mapa: Evidence Gap Map - Teledentistry

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/teleodontologia-en/evidence-map

Sugestão de cores para eixos x e y:
Para Intervenções - Interventions - usar cor #99CCFF com letra cor preto #080808
Para Desfechos - Outcomes - usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Evidence map (general)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Evidence map (by confidence level)
High – bolha cor verde #17A11A
Low – bolha cor azul #00B0F0
Critically low  – bolha cor vermelho #FF0000
Moderate – bolha cor laranja #FFA74F

Aba 3: Evidence map (by intervention effect)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Intervention effect
Inconclusive - #F57BDB
Negative - #FF0000
Potential negative - #FFC000
Positive - #007E00
Potential positive - #81F7A6
No effect - #00B0F0
Not reported – #4C5E6C

Aba 4: Main findings (arquivo em anexo)

Aba 5: About (arquivo em anexo)
Nas abas 1, 2 e 3:

Grupo de desfechos na horizontal
Desfechos na vertical

Para Intervenções – Interventions -  usar cor #99CCFF com letra cor preto #080808
Para Desfechos – Outcomes -  usar cor #93E9D2 para o fundo e letra preto #080808

Incluir os seguintes 4 filtros: Outcomes (dados da coluna “outcomes”); Intervention effect (Effects); Population; Country/Region Focus
[About EGM Teledentistry atualização.docx](https://github.com/bireme/data-governance/files/14314793/About.EGM.Teledentistry.atualizacao.docx)
[Atualização_Caracterizacao_Mapa_Teleodonto_Ingles_14fev2024_processamento.xlsx](https://github.com/bireme/data-governance/files/14314794/Atualizacao_Caracterizacao_Mapa_Teleodonto_Ingles_14fev2024_processamento.xlsx)
[Main findings_Evidence map teledentistry atualizado.docx](https://github.com/bireme/data-governance/files/14314795/Main.findings_Evidence.map.teledentistry.atualizado.docx)

**Comment by veronicaabdala** [comment]
por favor considerar esta planilha
[Atualização_Caracterizacao_Mapa_Teleodonto_Ingles_14fev2024_versao_processamento.xlsx](https://github.com/bireme/data-governance/files/14318899/Atualizacao_Caracterizacao_Mapa_Teleodonto_Ingles_14fev2024_versao_processamento.xlsx)

**Comment by anakatiacamilo** [comment]
![image](https://github.com/bireme/data-governance/assets/19270675/2fd098ba-7bcc-4aa5-ad32-17d95dfea7da)
