### ISSUE TITLE
Mapa de evidências – Laser no tratamento de Lesões por Pressão

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#399]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidências – Laser no tratamento de Lesões por Pressão

URL sugerida: 
https://public.tableau.com/app/profile/bireme/viz/laser-lesao-pressao-pt/evidence-map 

Sugestão de cores para eixos x e y:

Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #1F7B1F
Potencial positivo - #A2E8A2
Sem efeito - #00B0F0

Aba 4: Resumo (principais achados)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Grupo de interventions na vertical
Interventions na horizontal

Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 4
[Uploading planilha final mapa laser em lesao por pressao 19fev24.xlsx…]()
 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco

**Comment by anakatiacamilo** [comment]
@veronicaabdala, não consigo fazer o upload do arquivo quando tem a palavra Uploading planilha e ... no final 
![image](https://github.com/bireme/data-governance/assets/19270675/e9d3a01f-7c25-41ee-915c-bee0669499e6)

Poderia tentar novamente ou me mandar de outra forma.

**Comment by veronicaabdala** [comment]
Aproveito para reenviar o texto sobre e resumo com uma pequena correção.

E o título do mapa considerar: 

Terapia de Fotobiomodulação no tratamento de Lesão por Pressão

[planilha final mapa laser em lesao por pressao 19fev24.xlsx](https://github.com/bireme/data-governance/files/14359959/planilha.final.mapa.laser.em.lesao.por.pressao.19fev24.xlsx)
[Resumo mapa Laser em lesão por pressão 21fev24.docx](https://github.com/bireme/data-governance/files/14359963/Resumo.mapa.Laser.em.lesao.por.pressao.21fev24.docx)
[sobre mapa Laser em lesão por pressão 21fev24.docx](https://github.com/bireme/data-governance/files/14359964/sobre.mapa.Laser.em.lesao.por.pressao.21fev24.docx)

**Comment by anakatiacamilo** [comment]
Mapa disponível, por favor, verificar.

Tive que fazer alterações no arquivo original, por favor, usar o arquivo abaixo para futuras atualizações.

[evidence-map2process.xlsx](https://github.com/bireme/data-governance/files/14366067/evidence-map2process.xlsx)

**Comment by veronicaabdala** [comment]
vc pode por favor considerar este arquivo sobre atualizado de novo - desculpa, mas a todo momento a revisora me pede uma coisa. 
[Uploading sobre mapa Laser em lesão por pressão 21fev24.docx…]()

**Comment by veronicaabdala** [comment]
[sobre mapa Laser em lesão por pressão 21fev24.docx](https://github.com/bireme/data-governance/files/14373755/sobre.mapa.Laser.em.lesao.por.pressao.21fev24.docx)
[sobre mapa Laser em lesão por pressão 21fev24.docx](https://github.com/bireme/data-governance/files/14373806/sobre.mapa.Laser.em.lesao.por.pressao.21fev24.docx)

veja se funcionou o upload do arquivo

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
