### ISSUE TITLE
Mapa arboviroses - atualizado 2024 - urgente

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#400]
Por favor reprocessar para atualizar o Mapa de evidências - Arboviroses: estratégias de prevenção e controle, disponível na URL https://public.tableau.com/app/profile/bireme/viz/arboviroses-pt/evidence-map

Considerar as mesmas especificações. O mapa foi atualizado agora em 2024 e agregou novos estudos.

Precisa atualizar a aba resumo e sobre o mapa.

[Mapa Caracterizacao_Arboviroses_processamento_fev2024.xlsx](https://github.com/bireme/data-governance/files/14436985/Mapa.Caracterizacao_Arboviroses_processamento_fev2024.xlsx)
[sobre_mapa_evidencia_arboviroses fev2024.docx](https://github.com/bireme/data-governance/files/14436992/sobre_mapa_evidencia_arboviroses.fev2024.docx)
[resumo_mapa_evidencia_arboviroses_fev2024.docx](https://github.com/bireme/data-governance/files/14436995/resumo_mapa_evidencia_arboviroses_fev2024.docx)

**Comment by anakatiacamilo** [comment]
@veronicaabdala, tem um documento nesta planilha que tem o mesmo título, mas o número e a classificação bem diferentes ( 39 / 54 - Randomized trials of housing interventions to prevent malaria and Aedes-transmitted diseases: A systematic review and meta-analysis), poderia verificar?

![image](https://github.com/bireme/data-governance/assets/19270675/970e0449-76ff-41fd-b80d-b84531474a8b)

**Comment by veronicaabdala** [comment]
reenviando com correção

[Mapa Caracterizacao_Arboviroses_processamento_fev2024.xlsx](https://github.com/bireme/data-governance/files/14487161/Mapa.Caracterizacao_Arboviroses_processamento_fev2024.xlsx)
[resumo_mapa_evidencia_arboviroses_fev2024.docx](https://github.com/bireme/data-governance/files/14487162/resumo_mapa_evidencia_arboviroses_fev2024.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
