### ISSUE TITLE
Mapa de evidências - Estratégias em Programas e Políticas de Alimentação e Nutrição

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#402]
Por favor atualizar o texto resumo e sobre do mapa  Estratégias em Programas e Políticas de Alimentação e Nutrição
disponível em: https://public.tableau.com/app/profile/bireme/viz/pnan-pt/evidence-map 

[resumo_mapa_PNAN_atualizado_1mar24.docx](https://github.com/bireme/data-governance/files/14461645/resumo_mapa_PNAN_atualizado_1mar24.docx)
[Sobre_Mapa_PNAN_atualizado_mar24.docx](https://github.com/bireme/data-governance/files/14461646/Sobre_Mapa_PNAN_atualizado_mar24.docx)

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
