### ISSUE TITLE
Mapa de evidencias – Cannabis Medicinal - em espanhol

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#403]
Processar o mapa em espanhol  com as seguintes especificações:

Título do mapa: Mapa de evidencias – Cannabis Medicinal

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/cannabis-medicinal-es/evidence-map  

Sugestão de cores para eixos x e y:
Para **Intervenciones** usar cor #99CCFF com letra cor preto #080808
Para **Desenlaces** usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidencias (General)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidencias (Nível de confianza)
Alto – bolha cor verde #17A11A
Bajo – bolha cor azul #00B0F0
Críticamente Bajo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
No si aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidencia (Efecto de la intervención)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efectos de la intervención
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #1F7B1F
Potencial positivo - #A2E8A2
Sin efecto - #00B0F0

Aba 4: Resumo (Hallazgos principales)

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 5 filtros: 
Desenlaces (dados da coluna “outcomes”); Efectos de la intervención; Población; País/Región Foco; Efectos Adversos

Nota: efeitos adversos é um índice novo, primeira vez que foi usado em mapa e está na última coluna S da planilha
[resumo_mapa_cannabis_epanhol.docx](https://github.com/bireme/data-governance/files/14575214/resumo_mapa_cannabis_epanhol.docx)
[sobre_mapa_cannabis_espanhol.docx](https://github.com/bireme/data-governance/files/14575215/sobre_mapa_cannabis_espanhol.docx)
[Cannabis_Caracterizacao_Revisões_23nov23_espanol.xlsx](https://github.com/bireme/data-governance/files/14575220/Cannabis_Caracterizacao_Revisoes_23nov23_espanol.xlsx)

**Comment by veronicaabdala** [comment]
Ah, desculpa, me esqueci. 

Revisando e corrigindo a tradução:

Sin efecto adverso
No evaluado

obrigada

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
