### ISSUE TITLE
Mapa de Evidencias - Infecções Urinárias na Gravidez

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#404]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidências – Infecções Urinárias na Gravidez

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/itu-embarazo-pt/evidence-map  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #009900
Potencial positivo - #ACD292
Sem efeito - #00B0F0
Similar/Indiferente - #241486

Aba 4: Resumo (principais achados) ** este texto ainda está em revisão - vou mandar o arquivo em separado

Aba 5: Sobre

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical
Usar cor nas células dos grupos de desfechos #C5E0B3 e grupos de intervenções #9CB6F8

Incluir os seguintes 5 filtros: Desfechos (dados da coluna “outcomes”); Efeitos da intervenção; População; País/Região Foco
[Mapa_ITU__processamento_port.xlsx](https://github.com/bireme/data-governance/files/14912149/Mapa_ITU__processamento_port.xlsx)
[acerca_mapa_ITU_embarazo.docx](https://github.com/bireme/data-governance/files/14912158/acerca_mapa_ITU_embarazo.docx)

**Comment by anakatiacamilo** [comment]
Publicado, esperando o resumo para atualizar.

**Comment by veronicaabdala** [comment]
Segue os dois textos atualizados: resumo e sobre

Também reenvio a planilha pois houve um ajuste no nome de um outcome - parto prematuro ficou parto pré-termo

Também solicito a inclusão do filtro Intervenções. Se precisar excluir algum, pode ser o filtro de efeito.

[sobre_mapa_ITU_gravidez.docx](https://github.com/bireme/data-governance/files/14935050/sobre_mapa_ITU_gravidez.docx)
[resumo_mapa_itu_embarazo_port.docx](https://github.com/bireme/data-governance/files/14935051/resumo_mapa_itu_embarazo_port.docx)
[Mapa_ITU__processamento_port.xlsx](https://github.com/bireme/data-governance/files/14935052/Mapa_ITU__processamento_port.xlsx)

**Comment by anakatiacamilo** [comment]
Atualizado
