### ISSUE TITLE
Mapa de evidencias – Infecciones Urinarias en el Embarazo

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#405]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de evidencias – Infecciones Urinarias en el Embarazo

URL sugerida: https://public.tableau.com/app/profile/bireme/viz/itu-embarazo-es/evidence-map

Sugestão de cores para eixos x e y:
Para Intervenciones usar cor #99CCFF com letra cor preto #080808
Para Desenlaces usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.

Aba 1: Mapa de evidencias (general)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidencias (por nivel de confianza)
Alto – bolha cor verde #17A11A
Bajo – bolha cor azul #00B0F0
Críticamente Bajo – bolha cor vermelho #FF0000

Aba 3: Mapa de evidencia (por efecto de la intervención)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efecto de la intervención
Inconcluso - #F57BDB
Negativo - #FF0000
Potencial negativo - #FFA74F
Positivo - #009900
Potencial positivo - #ACD292
Sin efecto - #00B0F0
Similar/Indiferente - #241486

Aba 4: Resúmen (principales resultados) 

Aba 5: Acerca

Nas abas 1, 2 e 3:
Grupo de desenlaces na horizontal
Desenlaces na vertical
Usar cor nas células dos grupos de desenlaces #C5E0B3 e grupos de intervenciones #9CB6F8

Incluir os seguintes 5 filtros: Desenlaces (dados da coluna “outcomes”); Intervenciones; Efecto de la Intervención; Población; País/Región Foco

[resumo_mapa_itu_embarazo_espanol.docx](https://github.com/bireme/data-governance/files/14982508/resumo_mapa_itu_embarazo_espanol.docx)
[acerca_mapa_ITU_embarazo_espanol.docx](https://github.com/bireme/data-governance/files/14982509/acerca_mapa_ITU_embarazo_espanol.docx)
[Mapa_ITU__processamento_espanol.xlsx](https://github.com/bireme/data-governance/files/14982511/Mapa_ITU__processamento_espanol.xlsx)

**Comment by anakatiacamilo** [comment]
Bom dia @veronicaabdala, 

O Mapa de Evidencia esta publicado, por favor, verifiar.
Tem duas colunas que não foram traduzidas para o espanhol  (Study Design e Review Design)

<img width="361" alt="image" src="https://github.com/bireme/data-governance/assets/19270675/f0fbab70-8703-49ee-bc59-209bbc317314">

E na ABA Interventions esta faltando um "Interventions Group" tanto na versão em es quanto na pt

![image](https://github.com/bireme/data-governance/assets/19270675/1e5a11fc-ba59-4950-9f5f-dbd8a351bb2a)
