### ISSUE TITLE
Mapa de Evidências Redução do Consumo de Bebidas Alcoólicas - Reprocessar

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#406]
Reprocessar o Mapa de Evidências Redução do Consumo de Bebidas Alcoólicas - https://public.tableau.com/app/profile/bireme/viz/consumo-bebidas-alcoolicas-pt/evidence-map 

Com os mesmos parâmetros e especificações.

Acrescentar INCA após o nome da BIREME/OPAS/OMS com vírgula para separar
[Mapa_bebidas_alcoólicas_020424_v7.xlsx](https://github.com/bireme/data-governance/files/15111990/Mapa_bebidas_alcoolicas_020424_v7.xlsx)

<img width="911" alt="image" src="https://github.com/bireme/data-governance/assets/26144462/6d636674-dab3-4b28-920d-375a360bee0f">
<img width="911" alt="Captura de tela 2024-04-25 115627" src="https://github.com/bireme/data-governance/assets/26144462/a0c66a85-ef72-460c-8077-84b077228af9">

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar

**Comment by veronicaabdala** [comment]
Está tudo certo, mas eles mandaram uma correção no resumo - principais achados. Segue a nova versão
[Mapa_bebidas_alcoolicas_300424_resumo.docx](https://github.com/bireme/data-governance/files/15187821/Mapa_bebidas_alcoolicas_300424_resumo.docx)

**Comment by anakatiacamilo** [comment]
Atualizado
