### ISSUE TITLE
Mapa de Evidências da Fotobiomodulação na Aceleração do Movimento Ortodôntico

### ISSUE THREAD

**Issue by veronicaabdala** [bireme/data-governance#407]
Processar o mapa com as seguintes especificações:

Título do mapa: Mapa de Evidências da Fotobiomodulação na Aceleração do Movimento Ortodôntico

URL sugerida: <https://public.tableau.com/app/profile/bireme/viz/fotobiomodulacao-pt/evidence-map>  

Sugestão de cores para eixos x e y:
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

O mapa terá 5 abas, sendo a primeira geral, conforme especificações abaixo.
Aba 1: Mapa de evidências (geral)
Criar uma primeira aba, geral, usar como parâmetro apenas a quantidade de associações, com bolhas de uma única cor roxo #00B0F0

Aba 2: Mapa de evidências (por nível de confiança)
Alto – bolha cor verde #17A11A
Baixo – bolha cor azul #00B0F0
Criticamente Baixo – bolha cor vermelho #FF0000
Moderado – bolha cor laranja #FFA74F
Não se aplica – bolha cor cinza #FFFFFF 

Aba 3: Mapa de evidência (por efeito da intervenção)
Usar como parâmetro de cores para as bolhas o campo “effects” e nomear como Efeito da intervenção
Inconclusivo - #F57BDB
Negativo - #FF0000
Potencial Negativo - #A70111
Positivo - #1F7B1F
Potencial Positivo - #A2E8A2
Sem efeito - #00B0F0
Não informado – #4C5E6C
Não se aplica - #0E1A8C

Aba 4: Resumo (principais achados)

Aba 5: Sobre 

Nas abas 1, 2 e 3:
Grupo de desfechos na horizontal
Desfechos na vertical

[resumo mapa fotobiomodulação 17mar2024.docx](https://github.com/bireme/data-governance/files/15278325/resumo.mapa.fotobiomodulacao.17mar2024.docx)
[sobre mapa fotobiomodulação 17mar2024.docx](https://github.com/bireme/data-governance/files/15278326/sobre.mapa.fotobiomodulacao.17mar2024.docx)
[Fotobiomodulaçao-Mapa-17mar2024.xlsx](https://github.com/bireme/data-governance/files/15278327/Fotobiomodulacao-Mapa-17mar2024.xlsx)
Para Intervenções usar cor #99CCFF com letra cor preto #080808
Para Desfechos usar cor #93E9D2 para o fundo e letra preto #080808

**Comment by anakatiacamilo** [comment]
Atualizado, por favor, verificar
https://public.tableau.com/app/profile/bireme/viz/fotobiomodulacao-pt/evidence-map
