### ISSUE TITLE
DECS - Enriquecimento de Descritores

### ISSUE THREAD

**Issue by lcorreasantos** [bireme/data-governance#53]
- Dados de conexão da Base de Dados do DECS
- Verificar o modelo de dados do DECS
- Criar processo de Carga para enriquecer a tabela de descritores

**Comment by dossanluc** [comment]
- Dados de conexão da Base de Dados do DECS --> OK

**Comment by dossanluc** [comment]
Carga de Thesaurus criada e em testes

**Comment by dossanluc** [comment]
Revisão do processo, validação e carga final.
