### ISSUE TITLE
Analisar processo atual - Arquivo Lucene

### ISSUE THREAD

**Issue by lcorreasantos** [bireme/data-governance#56]
- Analisar o processo de transformação de dados
- Analisar o processo de criação do arquivo XML para o Lucene

**Comment by dossanluc** [comment]
Reunião marcada com Marcelo

**Comment by dossanluc** [comment]
Primeira reunião de entendimento
- Conhecimento da estrutura do XML
- Entendimento dos capos PRI (primários - direto da base de dados) e SEC (secundários - gerados em tempo de processamento)
- Próximos passos
1. Gerar um arquivo com todos os campos (PRI e SEC (vazio))
2. Validar a estrutura do XML gerado
3. Tratar os campos SEC, um-a-um para finalizar a geraçõa do XML

**Comment by botturam** [comment]
Compartilho link da tabela de regras de criação e transformação de campos IAHx-Regional:

https://paho.sharepoint.com/:x:/s/BIR/TC/EZmIDJaPMfVCkhn6DrGB99MB9jr_0MpobXQNRcsTLSEsGQ?e=gCw7sK

**Comment by dossanluc** [comment]
- Criação da Transformação para gerar o arquivo lil_regional.xml

**Comment by dossanluc** [comment]
Após entendimento de todo o processo atual de geração do arquivo xml pra Lucene, será criado um processo similar em Python e para posteriomente incluir em um procecesso do Pentaho.

**Comment by dossanluc** [comment]
Criar estrutura para consulta em banco de dados.
from	meta_dados as m inner join autor_afiliacao as a on 
		m.id = a.id inner join descritores_qualificadores as d on 
		m.id = d.id inner join st_instituto as ai on 
		m.id = ai.id inner join st_base_dados as b on 
		m.id = b.id inner join st_resumo as r on 
		m.id = r.id inner join st_idiomas as im on 
		m.id = im.id inner join st_evento as ev on 
		m.id = ev.id inner join st_url as u on 
		m.id = u.id inner join st_autor_keywords as k on 
		m.id = k.id

**Comment by dossanluc** [comment]
Iniciando testes no Pentaho PDI e Pentaho Server com o gerarIAHX.py (programa em Python)

**Comment by dossanluc** [comment]
Analise finalizada, as demais implementações serão tratadas em issues específicas.
