### ISSUE TITLE
Visualiazações Tableau

### ISSUE THREAD

**Issue by lcorreasantos** [bireme/data-governance#57]
- Conectar o Tableau na nova estrutura de banco de dados - Governaça
- Atualizar os Dashboard Atuais

**Comment by dossanluc** [comment]
Primenira visulização ralizada;
Ajustar as consultas para nova validação.

**Comment by dossanluc** [comment]
Primeira validação de dados para visualização finalizada.
Serão criado novas issues para os próximos passos.
